// ==========================================
// 💡 一括登録用クイズ
// ==========================================
// 📝 大量に登録したいクイズデータの配列（1レコード1行仕様）

// 配列を空っぽで宣言
export const bulkQuestionsData = [];

// ==========================================
// 👶 幼児向け（grade: 0）クイズデータ
// ==========================================

// 🟥 【こくご：japanese】
bulkQuestionsData.push(...[
    { grade: 0, genre: "japanese", type: "select", text: "「ねこ」の さいしょの もじは なあに？", choices: ["ね", "こ", "い", "う"], answer: "ね", explanation: "せいかいは「ね」！<br><b>ね</b>・こ のさいしょのもじは<b>「ね」</b>だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "「ぞう」の おおきい はなは どこにある？", choices: ["かお", "おなか", "あし", "おしり"], answer: "かお", explanation: "せいかいは「かお」！<br>おはなが ながーい ぞうさんは、<b>かお</b>に はながあるよ！" },
    { grade: 0, genre: "japanese", type: "which", text: "「いぬ」を はんたいから よむと 「ぬい」になる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>うしろから よむと <b>ぬ・い</b> になるね！おもしろいね！" },
    { grade: 0, genre: "japanese", type: "select", text: "そらを とぶ とりは どれかな？", choices: ["すずめ", "らいおん", "くま", "きりん"], answer: "すずめ", explanation: "せいかいは「すずめ」！<br>すずめさんは <b>つばさ</b>を パタパタさせて そらを とぶよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "「りんご」の いろは なにいろかな？", choices: ["あか", "あお", "きいろ", "くろ"], answer: "あか", explanation: "せいかいは「あか」！<br>あまくて おいしい りんごは <span style='color:#e74c3c; font-weight:bold;'>あかいいろ</span> を しているよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "「うみ」に すんでいる いきものは どれ？", choices: ["たこ", "かぶとむし", "うさぎ", "ぽにー"], answer: "たこ", explanation: "せいかいは「たこ」！<br>たこさんは <b>うみの なか</b>で あしを くねくね させて およぐよ！" },
    { grade: 0, genre: "japanese", type: "which", text: "「あり」の もじの かずは 3つである。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>あ・り で <b>2つの もじ</b> だから、×（ばつ）だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "「あ」の つぎに くる もじは なあに？", choices: ["い", "う", "え", "お"], answer: "い", explanation: "せいかいは「い」！<br>あいうえお の じゅんばんは、<b>「あ」のつぎは「い」</b>だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "ワンワン と なく どうぶつは なあに？", choices: ["いぬ", "ねこ", "ねずみ", "うし"], answer: "いぬ", explanation: "せいかいは「いぬ」！<br>かわいい いぬさんは <b>ワンワン！</b> って 元気に なくよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "「ねこ」の さいしょの もじは なあに？", choices: ["ね", "こ", "い", "う"], answer: "ね", explanation: "せいかいは「ね」！<br><b>ね</b>・こ のさいしょのもじは<b>「ね」</b>だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "「ぞう」の おおきい はなは どこにある？", choices: ["かお", "おなか", "あし", "おしり"], answer: "かお", explanation: "せいかいは「かお」！<br>おはなが ながーい ぞうさんは、<b>かお</b>に はながあるよ！" },
    { grade: 0, genre: "japanese", type: "which", text: "「いぬ」を はんたいから よむと 「ぬい」になる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>うしろから よむと <b>ぬ・い</b> になるね！おもしろいね！" },
    { grade: 0, genre: "japanese", type: "select", text: "そらを とぶ とりは どれかな？", choices: ["すずめ", "らいおん", "くま", "きりん"], answer: "すずめ", explanation: "せいかいは「すずめ」！<br>すずめさんは <b>つばさ</b>を パタパタさせて そらを とぶよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "「りんご」の いろは なにいろかな？", choices: ["あか", "あお", "きいろ", "くろ"], answer: "あか", explanation: "せいかいは「あか」！<br>あまくて おいしい りんごは <span style='color:#e74c3c; font-weight:bold;'>あかいいろ</span> を しているよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "「うみ」に すんでいる いきものは どれ？", choices: ["たこ", "かぶとむし", "うさぎ", "ぽにー"], answer: "たこ", explanation: "せいかいは「たこ」！<br>たこさんは <b>うみの なか</b>で あしを くねくね させて およぐよ！" },
    { grade: 0, genre: "japanese", type: "which", text: "「あり」の もじの かずは 3つである。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>あ・り で <b>2つの もじ</b> だから、×（ばつ）だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "「あ」の つぎに くる もじは なあに？", choices: ["い", "う", "え", "お"], answer: "い", explanation: "せいかいは「い」！<br>あいうえお の じゅんばんは、<b>「あ」のつぎは「い」</b>だね！" },
    { grade: 0, genre: "japanese", type: "select", text: "ワンワン と なく どうぶつは なあに？", choices: ["いぬ", "ねこ", "ねずみ", "うし"], answer: "いぬ", explanation: "せいかいは「いぬ」！<br>かわいい いぬさんは <b>ワンワン！</b> って 元気に なくよ！" },
    { grade: 0, genre: "japanese", type: "select", text: "おてがみを かくときに つかうものは どれかな？", choices: ["えんぴつ", "はさみ", "すぷーん", "とけい"], answer: "えんぴつ", explanation: "せいかいは「えんぴつ」！<br><b>えんぴつ</b>を使って、じを かきかき しようね！" },
    { grade: 0, genre: "japanese", type: "which", text: "「くり」と「すいか」は、どちらも さいしょの文字が「く」である。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>すいかの さいしょのもじは <b>「す」</b> だからちがうね！" },
    { grade: 0, genre: "japanese", type: "select", text: "あめが ふったときに さすものは なあに？", choices: ["かさ", "くつ", "ぼうし", "かばん"], answer: "かさ", explanation: "せいかいは「かさ」！<br>雨（あめ）の日は <b>かさ</b>をさして おでかけしよう！" },
    { grade: 0, genre: "japanese", type: "select", text: "「めがね」を かける場所（ばしょ）は どこかな？", choices: ["め", "くち", "みみ", "あし"], answer: "め", explanation: "せいかいは「め」！<br>おめめの まえに <b>めがね</b>を かけて よく見えるようにするよ！" }
]);
// 🟦 【さんすう：math】
bulkQuestionsData.push(...[
    { grade: 0, genre: "math", type: "select", text: "りんごが 3こ あります。2こ もらうと、ぜんぶで なんこ？", choices: ["5こ", "4こ", "1こ", "6こ"], answer: "5こ", explanation: "せいかいは「5こ」だよ！<br>あわせるからたしざんだね。<b>3 ＋ 2 ＝ 5</b> になるよ！" },
    { grade: 0, genre: "math", type: "select", text: "「8」の つぎに おおきい かずは なに？", choices: ["9", "5", "11", "6"], answer: "9", explanation: "せいかいは「9」だよ！<br>1,2,3,4,5,6,7,8……と数えていくと、8のつぎは<b>「9」</b>だね！" },
    { grade: 0, genre: "math", type: "select", text: "くるまの タイヤは ぜんぶで なんこ あるかな？", choices: ["2こ", "3こ", "4こ", "5こ"], answer: "4こ", explanation: "せいかいは「4こ」！<br>ブーブー はしる くるまには <b>4つの タイヤ</b>が ついているよ！" },
    { grade: 0, genre: "math", type: "select", text: "ちょうちょが 1ぴき います。もう 1ぴき くると、なんびき？", choices: ["2ひき", "3ひき", "4ひき", "5ひき"], answer: "2ひき", explanation: "せいかいは「2ひき」！<br>1つに 1つを あわせると <b>1 + 1 = 2</b> に なるね！" },
    { grade: 0, genre: "math", type: "which", text: "「おつきさま」の かたちは しかくい。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>まんまる おつきさまは <span style='color:#f1c40f; font-weight:bold;'>まるい かたち</span> を しているよ！" },
    { grade: 0, genre: "math", type: "select", text: "あめが 4こ あります。1こ たべると、のこりは なんこ？", choices: ["2こ", "3こ", "4こ", "1こ"], answer: "3こ", explanation: "せいかいは「3こ」！<br>4つの うち 1つを ひくと <b>4 - 1 = 3</b> に なるね！" },
    { grade: 0, genre: "math", type: "select", text: "「10」と「2」は、どちらが 大きい（おおい）かな？", choices: ["10のほうが大きい", "2のほうが大きい", "おなじ大きさ", "くらべられない"], answer: "10のほうが大きい", explanation: "せいかいは「10のほうが大きい」！<br>10こ のほうが 2こ よりも <b>たくさん あって 大きい</b> ね！" },
    { grade: 0, genre: "math", type: "select", text: "きりんさんの くびと、ぶたさんの くび、ながいのは どっち？", choices: ["きりんさん", "ぶたさん", "おなじながさ", "わからない"], answer: "きりんさん", explanation: "せいかいは「きりんさん」！<br>きりんさんの 首（くび）は <b>びよーんと ながくて</b> おおきいね！" },
    { grade: 0, genre: "math", type: "which", text: "て の ゆびは、ぜんぶで 10ほん ある。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>みぎ手（5ほん）と ひだり手（5ほん）を あわせると <b>5 + 5 = 10ほん</b> だよ！" },
    { grade: 0, genre: "math", type: "select", text: "「3」の つぎに 大きい（おおい） かずは なあに？", choices: ["4", "2", "5", "1"], answer: "4", explanation: "せいかいは「4」！<br>1、2、3、の つぎは <b>「4」</b> に なるね！" },
    { grade: 0, genre: "math", type: "select", text: "さんかく（▲）の かどの かずは なんこ あるかな？", choices: ["3こ", "4こ", "5こ", "2こ"], answer: "3こ", explanation: "せいかいは「3こ」！<br>さんかくの とがっている かどは <b>3つ</b> あるよ！" },
    { grade: 0, genre: "math", type: "select", text: "くるまの タイヤは ぜんぶで なんこ あるかな？", choices: ["2こ", "3こ", "4こ", "5こ"], answer: "4こ", explanation: "せいかいは「4こ」！<br>ブーブー はしる くるまには <b>4つの タイヤ</b>が ついているよ！" },
    { grade: 0, genre: "math", type: "select", text: "ちょうちょが 1ぴき います。もう 1ぴき くると、なんびき？", choices: ["2ひき", "3ひき", "4ひき", "5ひき"], answer: "2ひき", explanation: "せいかいは「2ひき」！<br>1つに 1つを あわせると <b>1 + 1 = 2</b> に なるね！" },
    { grade: 0, genre: "math", type: "which", text: "「おつきさま」の かたちは しかくい。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>まんまる おつきさまは <span style='color:#f1c40f; font-weight:bold;'>まるい かたち</span> を しているよ！" },
    { grade: 0, genre: "math", type: "select", text: "あめが 4こ あります。1こ たべると、のこりは なんこ？", choices: ["2こ", "3こ", "4こ", "1こ"], answer: "3こ", explanation: "せいかいは「3こ」！<br>4つの うち 1つを ひくと <b>4 - 1 = 3</b> に なるね！" },
    { grade: 0, genre: "math", type: "select", text: "「10」と「2」は、どちらが 大きい（おおい）かな？", choices: ["10のほうが大きい", "2のほうが大きい", "おなじ大きさ", "くらべられない"], answer: "10のほうが大きい", explanation: "せいかいは「10のほうが大きい」！<br>10こ のほうが 2こ よりも <b>たくさん あって 大きい</b> ね！" },
    { grade: 0, genre: "math", type: "select", text: "きりんさんの くびと、ぶたさんの くび、ながいのは どっち？", choices: ["きりんさん", "ぶたさん", "おなじながさ", "わからない"], answer: "きりんさん", explanation: "せいかいは「きりんさん」！<br>きりんさんの 首（くび）は <b>びよーんと ながくて</b> おおきいね！" },
    { grade: 0, genre: "math", type: "which", text: "て の ゆびは、ぜんぶで 10ほん ある。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>みぎ手（5ほん）と ひだり手（5ほん）を あわせると <b>5 + 5 = 10ほん</b> だよ！" },
    { grade: 0, genre: "math", type: "select", text: "「3」の つぎに 大きい（おおい） かずは なあに？", choices: ["4", "2", "5", "1"], answer: "4", explanation: "せいかいは「4」！<br>1、2、3、の つぎは <b>「4」</b> に なるね！" },
    { grade: 0, genre: "math", type: "select", text: "さんかく（▲）の かどの かずは なんこ あるかな？", choices: ["3こ", "4こ", "5こ", "2こ"], answer: "3こ", explanation: "せいかいは「3こ」！<br>さんかくの とがっている かどは <b>3つ</b> あるよ！" },
    { grade: 0, genre: "math", type: "select", text: "サイコロの いちばん おおきい め（かず）は なあに？", choices: ["6", "5", "4", "3"], answer: "6", explanation: "せいかいは「6」！<br>しかくいサイコロには <b>1から6までの かず</b>が かいてあるよ！" },
    { grade: 0, genre: "math", type: "which", text: "2こ のイチゴと、2こ のミカン。あわせると 5こ になる。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>2 と 2 を あわせると <b>2 + 2 = 4こ</b> になるね！" },
    { grade: 0, genre: "math", type: "select", text: "ドーナツが 6こ あって、2こ もらうと ぜんぶで なんこ？", choices: ["8こ", "7こ", "6こ", "9こ"], answer: "8こ", explanation: "せいかいは「8こ」！<br>6こ に 2こ を たし算すると <b>6 + 2 = 8</b> になるね！" },
    { grade: 0, genre: "math", type: "select", text: "ノートが 3さつ あって、3さつ つかうと のこりは なんさつ？", choices: ["0さつ", "1さつ", "2さつ", "3さつ"], answer: "0さつ", explanation: "せいかいは「0さつ」！<br><b>3つ から 3つ を ひく</b>と、ぜんぶ なくなっちゃうね！" }
]);
// 🟩 【どうとく：moral】
bulkQuestionsData.push(...[
    { grade: 0, genre: "moral", type: "select", text: "ともだちの おもちゃを つかいたいとき、なんて 言う？", choices: ["かして,という", "だまって とる", "おこる", "なきだす"], answer: "かして,という", explanation: "せいかいは「かして,という」だよ！<br>だまってとるとおともだちがかなしむから、<b>「かして」</b>といってやさしくじゅんばんをまとうね。" },
    { grade: 0, genre: "moral", type: "select", text: "ごはんを たべるとき、さいしょに 言う あいさつは？", choices: ["ごちそうさま", "いただきます", "こんにちは", "ありがとう"], answer: "いただきます", explanation: "せいかいは「いただきます」だよ！<br>たべのものいのちや、つくってくれたひとに<span style='color:#ff7675; font-weight:bold;'>「ありがとう」のきもち</span>をこめていうたいせつなあいさつだね。" },
    { grade: 0, genre: "moral", type: "select", text: "おうちの ひとに プレゼントを もらったよ。なんて 言う？", choices: ["ありがとう", "ごめんなさい", "こんにちは", "バイバイ"], answer: "ありがとう", explanation: "せいかいは「ありがとう」！<br>うれしいことを してもらったときは <b>「ありがとう」</b> と おつたえしようね！" },
    { grade: 0, genre: "moral", type: "select", text: "おともだちの あしを うっかり ふんじゃった！なんて 言う？", choices: ["ごめんなさい", "ありがとう", "やったー", "わはは"], answer: "ごめんなさい", explanation: "せいかいは「ごめんなさい」！<br>わるいことを しちゃったときは <b>すぐ「ごめんなさい」</b> が できると かっこいいよ！" },
    { grade: 0, genre: "moral", type: "which", text: "よる 遅い（おそい）じかんに、おうちの なかで ドタバタ 走ってもよい。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>よるは みんなくつろぐ じかんだよ。おうちの なかでは <span style='color:#3498db; font-weight:bold;'>しずかに すごそうね</span>。" },
    { grade: 0, genre: "moral", type: "select", text: "あさ 起きた（おきた）とき、おうちの ひとに する あいさつは？", choices: ["おはよう", "おやすみ", "さようなら", "いただきます"], answer: "おはよう", explanation: "せいかいは「おはよう」！<br>あさ一番の <b>「おはよう！」</b> は とっても きもちがいいね！" },
    { grade: 0, genre: "moral", type: "select", text: "ごはんを 食べおわった（たべおわった）あとに 言う あいさつは？", choices: ["ごちそうさま", "いただきます", "こんにちは", "おじゃまします"], answer: "ごちそうさま", explanation: "せいかいは「ごごちそうさま」！<br>つくってくれた 人や、お野菜（やさい）さんに <b>「ごちそうさま」</b> っていおうね！" },
    { grade: 0, genre: "moral", type: "which", text: "おもちゃで 遊んだ（あそんだ）あとは、そのままにして 次のあそびをする。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>あそんだ あとは <b>「おかたづけ」</b> を してから つぎの あそびを しようね！" },
    { grade: 0, genre: "moral", type: "select", text: "おともだちが つかっている おもちゃを 自分も つかいたいとき、どうする？", choices: ["かして、と聞く", "むりやり奪う", "なげつける", "だまって取る"], answer: "かして、と聞く", explanation: "せいかいは「かして、と聞く」だよ！<br>やさしく <b>「かーしーてー」</b> って おはなし してみようね！" },
    { grade: 0, genre: "moral", type: "select", text: "外から おうちに 帰ってきた（かえってきた）ら、さいしょに することは？", choices: ["てあらい・うがい", "テレビをみる", "おやつをたべる", "ねる"], answer: "てあらい・うがい", explanation: "せいかいは「てあらい・うがい」！<br>バイキンを やっつけるために <span style='color:#2ecc71; font-weight:bold;'>ガラガラ・ブクブク</span> しようね！" },
    { grade: 0, genre: "moral", type: "which", text: "道路（どうろ）を わたるときは、みぎ と ひだり を しっかり 見てから わたる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>くるまが 来ないか <b>みぎ・ひだり・みぎ</b> を しっかり みて、てをあげて わたろうね！" },
    { grade: 0, genre: "moral", type: "select", text: "おうちの ひとに プレゼントを もらったよ。なんて 言（い）う？", choices: ["ありがとう", "ごめんなさい", "こんにちは", "バイバイ"], answer: "ありがとう", explanation: "せいかいは「ありがとう」！<br>うれしいことを してもらったときは <b>「ありがとう」</b> と おつたえしようね！" },
    { grade: 0, genre: "moral", type: "select", text: "おともだちの あしを うっかり ふんじゃった！なんて 言（い）う？", choices: ["ごめんなさい", "ありがとう", "やったー", "わはは"], answer: "ごめんなさい", explanation: "せいかいは「ごめんなさい」！<br>わるいことを しちゃったときは <b>すぐ「ごめんなさい」</b> が できると かっこいいよ！" },
    { grade: 0, genre: "moral", type: "which", text: "よる 遅い（おそい）じかんに、おうちの なかで ドタバタ はしってもよい。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>よるは みんなくつろぐ じかんだよ。おうちの なかでは <span style='color:#3498db; font-weight:bold;'>しずかに すごそうね</span>。" },
    { grade: 0, genre: "moral", type: "select", text: "あさ 起きた（おきた）とき、おうちの ひとに する あいさつは？", choices: ["おはよう", "おやすみ", "さようなら", "いただきます"], answer: "おはよう", explanation: "せいかいは「おはよう」！<br>あさいちばんの <b>「おはよう！」</b> は とっても きもちがいいね！" },
    { grade: 0, genre: "moral", type: "select", text: "ごはんを 食べおわった（たべおわった）あとに 言（い）う あいさつは？", choices: ["ごちそうさま", "いただきます", "こんにちは", "おじゃまします"], answer: "ごちそうさま", explanation: "せいかいは「ごちそうさま」！<br>つくってくれた 人や、お野菜（やさい）さんに <b>「ごちそうさま」</b> っていおうね！" },
    { grade: 0, genre: "moral", type: "which", text: "おもちゃで 遊んだ（あそんだ）あとは、そのままにして 次のあそびをする。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>あそんだ あとは <b>「おかたづけ」</b> を してから つぎの あそびを しようね！" },
    { grade: 0, genre: "moral", type: "select", text: "おともだちが つかっている おもちゃを じぶんも つかいたいとき、どうする？", choices: ["かして、ときく", "むりやりとる", "なげつける", "だまってとる"], answer: "かして、ときく", explanation: "せいかいは「かして、と聞（き）く」だよ！<br>やさしく <b>「かーしーてー」</b> って おはなし してみようね！" },
    { grade: 0, genre: "moral", type: "select", text: "外から おうちに 帰ってきた（かえってきた）ら、さいしょに することは？", choices: ["てあらい・うがい", "テレビをみる", "おやつをたべる", "ねる"], answer: "てあらい・うがい", explanation: "せいかいは「てあらい・うがい」！<br>バイキンを やっつけるために <span style='color:#2ecc71; font-weight:bold;'>ガラガラ・ブクブク</span> しようね！" },
    { grade: 0, genre: "moral", type: "which", text: "道路（どうろ）を わたるときは、みぎ と ひだり を しっかり 見（み）てから わたる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>くるまが こないか <b>みぎ・ひだり・みぎ</b> を しっかり みて、てをあげて わたろうね！" },
    { grade: 0, genre: "moral", type: "select", text: "廊下（ろうか）や お部屋（おへや）の なかは、どうやって いどうする？", choices: ["あるく", "はしる", "すべりだいする", "ジャンプする"], answer: "あるく", explanation: "せいかいは「あるく」！<br>おうちの なかで はしると ごっつんこして <b>あぶないから、あるこうね</b>！" },
    { grade: 0, genre: "moral", type: "which", text: "おともだちが ころんで 泣（な）いていたら、わらって いじめる。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>おともだちが いたいときは <b>「だいじょうぶ？」</b> って 助けてあげようね。" },
    { grade: 0, genre: "moral", type: "select", text: "おともだちの おうちに あそびに いったとき、お部屋（おへや）に はいる前（まえ）に いう あいさつは？", choices: ["おじゃまします", "ありがとう", "ごめんなさい", "バイバイ"], answer: "おじゃまします", explanation: "せいかいは「おじゃまします」！<br>よそのおうちにはいるときは <b>「おじゃまします」</b> と 元気（げんき）にいおうね！" },
    { grade: 0, genre: "moral", type: "select", text: "みんなで 使う（つかう） おもちゃは、どうやって つかうと いいかな？", choices: ["なかよくつかう", "ひとりでどくせんする", "なげつける", "こわす"], answer: "なかよくつかう", explanation: "せいかいは「なかよくつかう」！<br>みんなで <b>順番（じゅんばん）に 交代（こうたい）しながら</b> なかよく遊（あそ）ぼうね！" }
]);
// 🔬 【りか：science】
bulkQuestionsData.push(...[
    { grade: 0, genre: "science", type: "select", text: "おそらに キラキラ 光（ひか）る、よるに 見（み）えるものは なあに？", choices: ["ほし", "たいよう", "くも", "にじ"], answer: "ほし", explanation: "せいかいは「ほし」！<br>よるの おそらには <b>キラキラひかる おほしさま</b>が たくさんみえるよ！" },
    { grade: 0, genre: "science", type: "select", text: "はるに さく、ピンクいろの きれいな お花（はな）は なあに？", choices: ["さくら", "ひまわり", "どんぐり", "あさがお"], answer: "さくら", explanation: "せいかいは「さくら」！<br>あったかくなると <b>さくら</b>のはなが さいて、とってもきれいだね！" },
    { grade: 0, genre: "science", type: "which", text: "かえるさんは、お水（みず）の なかでも およぐことができる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>かえるさんは <b>お水（みず）のなかも、つちの うえも</b> どちらも大得意（だいとくい）だよ！" },
    { grade: 0, genre: "science", type: "select", text: "あおむしさんが 大き（おおき）くなると、なんの むしに へんしん するかな？", choices: ["ちょうちょ", "かぶとむし", "ばった", "あり"], answer: "ちょうちょ", explanation: "せいかいは「ちょうちょ」！<br>あおむしさんは <b>きれいな はねの ちょうちょ</b> に へんしんするよ！" },
    { grade: 0, genre: "science", type: "select", text: "ワンワン なく 犬（いぬ）の あしは ぜんぶで なんほん？", choices: ["4ほん", "2ほん", "6ほん", "8ほん"], answer: "4ほん", explanation: "せいかいは「4ほん」！<br>いぬさんや ねこさんの あしは <b>ぜんぶで 4ほん</b> あるよ！" },
    { grade: 0, genre: "science", type: "which", text: "雪（ゆき）は、あったかい お部屋（へや）に おいておくと お水（みず）になる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>つめたいゆきやこおりは、<b>あったかいと とけてお水（みず）になる</b>よ！" },
    { grade: 0, genre: "science", type: "select", text: "いけ の なかで スイスイ およぐ、あかい お魚（さかな）は なあに？", choices: ["きんぎょ", "めだか", "くじら", "いるか"], answer: "きんぎょ", explanation: "せいかいは「きんぎょ」！<br>あかくて ひらひら およぐ かわいいおさかなは <b>きんぎょ</b> だね！" },
    { grade: 0, genre: "science", type: "select", text: "あきに 木（き）から ぽとんと 落ち（お）ちてくる、ぼうしを かぶった木（き）の実は？", choices: ["どんぐり", "まつぼっくり", "りんご", "くり"], answer: "どんぐり", explanation: "せいかいは「どんぐり」！<br>森（もり）のどうぶつたちも大好きな <b>どんぐり</b> はあきにみつかるよ！" },
    { grade: 0, genre: "science", type: "which", text: "ありさんは、じぶんよりも 重（おも）たいものを はこぶことができる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>ありさんは からだはちいさいけれど、<b>とってもちからもち</b>なんだよ！" },
    { grade: 0, genre: "science", type: "select", text: "夏（なつ）の あさ、まぶしく 光（ひか）る おそらの おおきな丸（まる）いものは？", choices: ["たいよう", "おつきさま", "にじ", "くも"], answer: "たいよう", explanation: "せいかいは「たいよう」！<br>おひるをあかるく、<b>あったかくしてくれるのは 太陽（たいよう）</b>だね！" },
    { grade: 0, genre: "science", type: "select", text: "あさがおの 花（はな）が さくのは、1日（にち）のうちの いつかな？", choices: ["あさ", "よる", "おひる", "ゆうがた"], answer: "あさ", explanation: "せいかいは「あさ」！<br><b>あさがお</b> は、そのなまえのどおり <b>朝（あさ）はやく</b> にきれいなはなをさかせるよ！" },
    { grade: 0, genre: "science", type: "which", text: "すいか は、木（き）の うえに みのる。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br>すいか はきの上ではなく、<b>つちの うえを はうツル</b>になるんだよ！" },
    { grade: 0, genre: "science", type: "select", text: "とっても首（くび）がながい、黄色（きいろ）と茶色の模様（もよう）の動物（どうぶつ）は？", choices: ["きりん", "ぞう", "らいおん", "しまうま"], answer: "きりん", explanation: "せいかいは「きりん」！<br>たかいきの上のはっぱもとどく、<b>くびのながいどうぶつは きりん</b>さんだね！" },
    { grade: 0, genre: "science", type: "select", text: "海（うみ）にすんでいる、おでこから ピューと 水（みず）をふく 大き（おおき）な生きものは？", choices: ["くじら", "さめ", "たこ", "かに"], answer: "くじら", explanation: "せいかいは「くじら」！<br>うみのなかで一番（いちばん）おおきな <b>くじら</b>さんは、せなかからしおをふくよ！" }
]);
// 🗺️ 【しゃかい：social】
bulkQuestionsData.push(...[
    { grade: 0, genre: "social", type: "select", text: "まちの 安全（あんぜん）を まもってくれる、赤（あか）い くるまは なあに？", choices: ["しょうぼうしゃ", "ぱとかー", "きゅうきゅうしゃ", "たくしー"], answer: "しょうぼうしゃ", explanation: "せいかいは「しょうぼうしゃ」！<br>かじ のときに <span style='color:#e74c3c; font-weight:bold;'>あかいしょうぼうしゃ</span> が ビュービューはしってひをけすよ！" },
    { grade: 0, genre: "social", type: "select", text: "おてがみや ハガキを おうちに 届（とど）けてくれるのは だれかな？", choices: ["ゆうびんやさん", "はいしゃさん", "おまわりさん", "やきゅうしゅ"], answer: "ゆうびんやさん", explanation: "せいかいは「ゆうびんやさん」！<br>カバンに たくさんのおてがみをいれて、<b>おうちに届（とど）けてくれる</b>よ！" },
    { grade: 0, genre: "social", type: "which", text: "信号（しんごう）が「青（あお）」のときは、すすんでもよい。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>あおはすすむ、<b>あかはとまる</b>。しっかりまもって わたろうね！" },
    { grade: 0, genre: "social", type: "select", text: "びょうきや ケガをした人を、いそいで 病院（びょういん）へ運（はこ）ぶ 白（しろ）い車（くるま）は？", choices: ["きゅうきゅうしゃ", "ぱとかー", "とらっく", "ばす"], answer: "きゅうきゅうしゃ", explanation: "せいかいは「きゅうきゅうしゃ」！<br>ピーポーピーポーと <b>きゅうきゅうしゃ</b> がいそいではこんでくれるよ！" },
    { grade: 0, genre: "social", type: "select", text: "まちの パトロールをして、みんなを助（たす）けてくれる 警察（けいさつ）の車（くるま）は？", choices: ["ぱとかー", "しょうぼうしゃ", "ごみしゅうしゅうしゃ", "ぶるどーざー"], answer: "ぱとかー", explanation: "せいかいは「ぱとかー」！<br>白（しろ）とくろの <b>ぱとかー（パトカー）</b> にのって、おまわりさんがまもってくれるよ！" },
    { grade: 0, genre: "social", type: "which", text: "お買い物（かいもの）をするときは、お、お金（かね）をはらってから 品物（しなもの）をもらう。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>お店（みせ）のルールだね。<b>お金（かね）をちゃんとはらってから</b>おかいものしようね！" },
    { grade: 0, genre: "social", type: "select", text: "おいしい お米（こめ）や お野菜（やさい）を、畑（はたけ）でつくってくれるのはだれ？", choices: ["のうかさん", "ぎょにん", "うんてんしゅ", "うちゅうひこうし"], answer: "のうかさん", explanation: "せいかいは「のうかさん」！<br>まいにちおいしいごはんがたべられるのは、<b>のうかさん</b>のおかげだね！" },
    { grade: 0, genre: "social", type: "select", text: "たくさんの人を のせて、線路（せんろ）のうえを ガタンゴトン走（はし）る 乗りものは？", choices: ["でんしゃ", "ひこうき", "ふね", "じてんしゃ"], answer: "でんしゃ", explanation: "せいかいは「でんしゃ」！<br>駅（えき）からえきへ、<b>たくさんのひとをはこぶのは 電車（でんしゃ）</b>だね！" },
    { grade: 0, genre: "social", type: "which", text: "バスや 電車（でんしゃ）に のるときは、ならんでいる順番（じゅんばん）を まもってのる。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>みんながつかうのりものだね。<b>じゅんばんをしっかり守（まも）って</b>ならぼうね！" },
    { grade: 0, genre: "social", type: "select", text: "あたまに 白（しろ）いぼうしをかぶって、おいしい ケーキをつくってくれる人は？", choices: ["ぱてぃしえ", "かんごし", "しょうぼうし", "せんせい"], answer: "ぱてぃしえ", explanation: "せいかいは「ぱてぃしえ」！<br>あまくておいしい <b>おかしやケーキの職人（しょくにん）さん</b>だよ！" },
    { grade: 0, genre: "social", type: "select", text: "おうちの 前（まえ）に置いておいた ゴミを、大きな車（くるま）で あつめにきてくれる人は？", choices: ["ごみ収集の人", "たくはいびんの人", "大工さん", "おまわりさん"], answer: "ごみ収集の人", explanation: "せいかいは「ごみしゅうしゅうの人」！<br>まちをいつもきれいにするために、<b>ごみしゅうしゅうしゃ</b>であつめてくれるよ！" },
    { grade: 0, genre: "social", type: "which", text: "自分の お家（うち）がある 国（くに）の 名前（なまえ）は「にほん」である。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>わたしたちがくらしているこのくには <b>日本（にほん）</b> というんだよ！" },
    { grade: 0, genre: "social", type: "select", text: "髪（かみ）の毛（け）を チョキチョキ かっこよく・かわいく切（き）ってくれるお店（みせ）は？", choices: ["床屋・美容室", "本屋さん", "ケーキ屋さん", "おもちゃ屋さん"], answer: "床屋・美容室", explanation: "せいかいは「とこや・びようしつ」！<br>はさみをじょうずに使（つか）って、<b>かみのけをすっきりきれいにしてくれる</b>よ！" },
    { grade: 0, genre: "social", type: "select", text: "そらの うえを ビューンと飛（と）んで、遠（とお）くの国（くに）まで 運（はこ）んでくれる 大き（おおき）な乗りものは？", choices: ["ひこうき", "へりこぷたー", "新幹線", "ロケット"], answer: "ひこうき", explanation: "せいかいは「ひこうき」！<br>おおきなしろいはねをつけて <b>おそらを飛（と）ぶのは 飛行機（ひこうき）</b>だね！" }
]);
// 🔤 【えいご：english】
bulkQuestionsData.push(...[
    { grade: 0, genre: "english", type: "select", text: "えいごで 「アップル」といえば、なんの フルーツかな？", choices: ["りんご", "みかん", "ばなな", "ぶどう"], answer: "りんご", explanation: "せいかいは「りんご」！<br>まっかな りんごは えいごで <b>Apple（アップル）</b> っていうんだよ！" },
    { grade: 0, genre: "english", type: "select", text: "えいごで 「ドッグ」と なく どうぶつは なあに？", choices: ["いぬ", "ねこ", "うさぎ", "くま"], answer: "いぬ", explanation: "せいかいは「いぬ」！<br>いぬさんは えいごで <b>Dog（ドッグ）</b> っていうんだよ。ワンワン！" },
    { grade: 0, genre: "english", type: "select", text: "えいごで 「レッド」といえば、なにいろの ことかな？", choices: ["あか", "あお", "きいろ", "みどり"], answer: "あか", explanation: "せいかいは「あか」！<br>しょうぼうしゃの <span style='color:#e74c3c; font-weight:bold;'>赤（あか）いろは えいごで Red（レッド）</span> だよ！" },
    { grade: 0, genre: "english", type: "select", text: "えいごで 「ブルー」といえば、なにいろの ことかな？", choices: ["あお", "あか", "きいろ", "しろ"], answer: "あお", explanation: "せいかいは「あお」！<br>おそらや ひろいうみの <span style='color:#3498db; font-weight:bold;'>青（あお）いろは えいごで Blue（ブルー）</span> だよ！" },
    { grade: 0, genre: "english", type: "which", text: "えいごで 「ハロー」と いわれたら、あいさつの おへんじをする。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br><b>Hello（ハロー）</b> は「こんにちは」だから、元気にハローとおかえししよう！" },
    { grade: 0, genre: "english", type: "select", text: "すうじの 「1（いち）」を、えいごでいうと なあに？", choices: ["One", "Two", "Three", "Four"], answer: "One", explanation: "せいかいは「One（ワン）」！<br>一（いち）、二（に）、三（さん）は えいごで <b>One（ワン）、Two（ツー）、Three（スリー）</b> だね！" },
    { grade: 0, genre: "english", type: "select", text: "えいごで 「バナナ」の さいしょの 文字（もじ）は なあに？", choices: ["B", "A", "C", "M"], answer: "B", explanation: "せいかいは「B」！<br>きいろくて おいしいバナナは <b>Banana</b> なので、<b>「B」</b>から はじまるよ！" },
    { grade: 0, genre: "english", type: "which", text: "えいごで 「バイバイ」は、あさ 起（お）きたときに いう あいさつである。○か×か？", choices: [true, false], answer: false, explanation: "せいかいは ×（ばつ）！<br><b>Bye-bye（バイバイ）</b> は、おともだちと<b>「さようなら」</b>をして わかれるときの ことばだよ！" },
    { grade: 0, genre: "english", type: "select", text: "大（おお）きな お耳（みみ）の 「うさぎ」さんを、えいごでいうと なあに？", choices: ["Rabbit", "Bear", "Monkey", "Lion"], answer: "Rabbit", explanation: "せいかいは「Rabbit（ラビット）」！<br>ぴょんぴょん はねる うさぎさんは <b>Rabbit（ラビット）</b> っていうんだよ！" },
    { grade: 0, genre: "english", type: "select", text: "すうじの 「3（さん）」を、えいごでいうと なあに？", choices: ["Three", "Two", "One", "Four"], answer: "Three", explanation: "せいかいは「Three（スリー）」！<br>ゆびを 三（さん）ほん 立て（た）て <b>Three（スリー）</b> と かぞえてみようね！" },
    { grade: 0, genre: "english", type: "which", text: "えいごで 「ミルク」といえば、白（しろ）い ぎゅうにゅう のことである。○か×か？", choices: [true, false], answer: true, explanation: "せいかいは ○（まる）！<br>朝（あさ）ごはんで のむ おいしいぎゅうにゅうは <b>Milk（ミルク）</b> というんだよ！" },
    { grade: 0, genre: "english", type: "select", text: "えいごで 「イエロー」といえば、なんの いろかな？", choices: ["きいろ", "みどり", "ピンク", "くろ"], answer: "きいろ", explanation: "せいかいは「きいろ」！<br>あまくて おいしいレモンやバナナは <b>Yellow（イエロー）</b> だね！" },
    { grade: 0, genre: "english", type: "select", text: "みんなが大好き（だいすき）などうぶつ 「くま」さんを、えいごでいうと なあに？", choices: ["Bear", "Lion", "Tiger", "Fox"], answer: "Bear", explanation: "せいかいは「Bear（ベア）」！<br>もりにおおきなくまさんは <b>Bear（ベア）</b> というんだよ！" }
]);

// ==========================================
// 🎒 小学校4年生向け（grade: 4）クイズデータ追加
// ==========================================
// 🟥 【こくご：japanese】
bulkQuestionsData.push(...[
    { grade: 4, genre: "japanese", type: "select", text: "「新聞（しんぶん）に意見（いけん）を（ ）する」空欄に入る正しい漢字はどれ？", choices: ["投稿", "同行", "結構", "慣行"], answer: "投稿", explanation: "正解は「投稿（とうこう）」！<br>自分の意見や文章を新聞や雑誌に載せてもらうために送ることを<b>「投稿」</b>と言います。" },
    { grade: 4, genre: "japanese", type: "select", text: "「他人の行動を見て、自分の行いを改める」という意味の四字熟語はどれ？", choices: ["反面教師", "単刀直入", "以心伝心", "弱肉強食"], answer: "反面教師", explanation: "正解は「反面教師（はんめんきょうし）」！<br>悪い見本であっても、それを見て<b>「自分は気をつけよう」</b>と学ぶことができるという意味だよ。" },
    { grade: 4, genre: "japanese", type: "which", text: "「先生が参る（まいる）」という表現は、先生への敬語（尊敬語）として正しい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>「参る」は自分がへりくだる謙譲語（けんじょうご）だよ。先生が来るときは<span style='color:#e74c3c; font-weight:bold;'>「お見えになる」や「来られる」</span>が正しいよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「（ ）も歩けば棒に当たる」ということわざの空欄に入る動物はなに？", choices: ["犬", "猫", "猿", "鳥"], answer: "犬", explanation: "正解は「犬（いぬ）」！<br>何か行動を起こせば、<b>思いがけない幸運（または災難）にめぐり合う</b>という意味のことわざだよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「一億（いちおく）」は、一万（いちまん）の何倍の大きさかな？", choices: ["100倍", "1000倍", "10000倍", "10倍"], answer: "10000倍", explanation: "正解は「10000倍（一万倍）」！<br>4年生で習う大きな数だね。一万が10000個集まると<b>「一億」</b>という大きな単位になるんだよ！" },
    { grade: 4, genre: "japanese", type: "select", text: "慣用句（かんようく）の問題だよ。「（ ）を広くする」で、たくさんの知り合いを作るという意味になる言葉はどれ？", choices: ["顔", "耳", "目", "手"], answer: "顔", explanation: "正解は「顔（かお）」！<br><b>「顔が広い」</b>と言うと、いろいろなジャンルにたくさんの知り合いや友達がいる人のことを指すよ。" },
    { grade: 4, genre: "japanese", type: "which", text: "辞書（じしょ）で言葉を調べるとき、「あめ（雨）」は「あき（秋）」よりも後ろに載っている。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>50音順で比べると、「あ<b>き</b>」の「き」よりも、「あ<b>め</b>」の「め」のほうが後ろにあるからだね！" },
    { grade: 4, genre: "japanese", type: "select", text: "同じ漢字で読み方が違う言葉だよ。「地面（じめん）に［植える］」と「［植木］（うえき）」。［ ］の漢字の正しい訓読み（くんよみ）はどれ？", choices: ["う（える）", "そだ（てる）", "さ（く）", "は（やす）"], answer: "う（える）", explanation: "正解は「う（える）」！<br>植物を土にセットすることは<b>「植える（うえる）」</b>、音読みでは「植物（しょくぶつ）」の「ショク」と読むよ。" },
    { grade: 4, genre: "japanese", type: "direct", text: "「初志貫徹（しょしかんてつ）」のように、漢字が4つ組み合わさって特別な意味を持つ言葉を何熟語という？（ひらがなで入力してね）", choices: [], answer: "よじじゅくご", explanation: "正解は「よじじゅくご（四字熟語）」だよ！<br>4つの漢字で<b>深い意味や教訓</b>を表す、とても便利な言葉の組み合わせなんだ。" },
    { grade: 4, genre: "japanese", type: "select", text: "文章のつながりを作る言葉だよ。「昨日は雨が降った。（ ）、遠足は中止になった。」空欄に入る最も適切な言葉はどれ？", choices: ["だから", "しかし", "または", "ちなみに"], answer: "だから", explanation: "正解は「だから」！<br>前の出来事が原因（雨）になって、後ろの結果（中止）につながるため、<b>順接（じゅんせつ）の「だから」</b>を使うよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「他人の行動を見て、自分の行いを改める」という意味の四字熟語は？", choices: ["反面教師", "単刀直入", "以心伝心", "弱肉強食"], answer: "反面教師", explanation: "正解は「反面教師」だよ！<br>悪い見本（反面）を、自分を教えてくれる<b>「教師」</b>だと思って学びにするという意味だよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "次のうち、「敬語（尊敬語）」として正しいものはどれ？", choices: ["先生がお見えになる", "先生が来る", "先生が参る", "先生が来られる"], answer: "先生がお見えになる", explanation: "正解は「先生がお見えになる」だよ！<br>相手を高める最高の表現が<b>「お見えになる」</b>だよ。「参る」は自分がへりくだる謙譲語だから間違いやすいね。" },
    { grade: 4, genre: "japanese", type: "select", text: "「一生懸命」と同じ意味の言葉はどれ？", choices: ["必死になって", "てきとうに", "のんびりと", "おこりながら"], answer: "必死になって", explanation: "「一生懸命」は、命をかけるくらい<span style='color:red; font-weight:bold;'>全力でがんばる</span>という意味の四字熟語だよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「新聞（しんぶん）に意見（いけん）を（ ）する」カッコに入る正しい言葉はどれ？", choices: ["投稿", "同行", "結構", "慣行"], answer: "投稿", explanation: "正解は「投稿（とうこう）」！<br>自分の意見や文章を新聞や雑誌に載せてもらうために送ることを<b>「投稿（とうこう）」</b>と言います。" },
    { grade: 4, genre: "japanese", type: "select", text: "「他人の行動を見て、自分の行いを改める」という意味の四字熟語（よじじゅくご）はどれ？", choices: ["反面教師", "単刀直入", "以心伝心", "弱肉強食"], answer: "反面教師", explanation: "正解は「反面教師（はんめんきょうし）」！<br>悪い見本であっても、それを見て<b>「自分は気をつけよう」</b>と学ぶことができるという意味だよ。" },
    { grade: 4, genre: "japanese", type: "which", text: "「先生が参る（まいる）」という言い方は、先生への敬語（けいご）として正しい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>「参る」は自分がへりくだる言葉だよ。先生が来るときは<span style='color:#e74c3c; font-weight:bold;'>「お見えになる」や「来られる」</span>が正しいよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「（ ）も歩けば棒に当たる」ということわざのカッコに入る動物（どうぶつ）はなに？", choices: ["犬", "猫", "猿", "鳥"], answer: "犬", explanation: "正解は「犬（いぬ）」！<br>何か行動を起こせば、<b>思いがけない幸運（または災難）にめぐり合う</b>という意味のことわざだよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「一億（いちおく）」は、一万（いちまん）の何倍の大きさかな？", choices: ["100倍", "1000倍", "10000倍", "10倍"], answer: "10000倍", explanation: "正解は「10000倍（一万倍）」！<br>一万が10000個集まると<b>「一億（いちおく）」</b>という大きな単位（たんい）になるんだよ！" },
    { grade: 4, genre: "japanese", type: "select", text: "慣用句（かんようく）の問題だよ。「（ ）を広くする」で、たくさんの知り合いを作るという意味になるのはどれ？", choices: ["顔", "耳", "目", "手"], answer: "顔", explanation: "正解は「顔（かお）」！<br><b>「顔が広い」</b>と言うと、いろいろなところにたくさんの知り合いや友達がいる人のことを指すよ。" },
    { grade: 4, genre: "japanese", type: "which", text: "辞書（じしょ）で言葉を調べるとき、「あめ」は「あき」よりも後ろに載（の）っている。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>50音順で比べると、「あ<b>き</b>」の「き」よりも、「あ<b>め</b>」の「め」のほうが後ろにあるからだね！" },
    { grade: 4, genre: "japanese", type: "select", text: "同じ漢字で読み方が違う言葉だよ。「土に植（う）える」と「植木（うえき）」。［植木］の［植］の正しい訓読（くんよ）みはどれ？", choices: ["う（える）", "そだ（てる）", "さ（く）", "は（やす）"], answer: "う（える）", explanation: "正解は「う（える）」！<br>植物（しょくぶつ）を土にセットすることは<b>「植（う）える」</b>、音読みでは「植物」の「ショク」と読むよ。" },
    { grade: 4, genre: "japanese", type: "direct", text: "漢字が4つ組み合わさって特別な意味を表す言葉を何熟語（じゅくご）という？（ひらがなで入れてね）", choices: [], answer: "よじじゅくご", explanation: "正解は「よじじゅくご（四字熟語）」だよ！<br>4つの漢字で<b>深い意味や教え</b>を表す、とても便利な言葉の組み合わせなんだ。" },
    { grade: 4, genre: "japanese", type: "select", text: "文章（ぶんしょう）のつながりを作る言葉だよ。「昨日は雨が降った。（ ）、遠足は中止になった。」カッコに入るものはどれ？", choices: ["だから", "しかし", "または", "ちなみに"], answer: "だから", explanation: "正解は「だから」！<br>前の出来事が原因（あめ）になって、後ろの結果（ちゅうし）につながるため、<b>「だから」</b>を使うよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「はははと大きな声で笑う」の「ははは」のように、音（おと）を表した言葉をなんという？", choices: ["ぎおんご", "たいげん", "どうし", "れんたいし"], answer: "ぎおんご", explanation: "正解は「ぎおんご」！<br>物の音や動物の鳴き声などを、文字で表した言葉のことを<b>「ぎおんご」</b>というよ。" },
    { grade: 4, genre: "japanese", type: "which", text: "「はな（花）」という言葉の反対の意味の言葉は「はっぱ」である。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>「はな」に反対の意味の言葉はないよ。物の名前には反対がないことが多いんだ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「自分の考えをまとめる」の「まとめる」と同じ意味の言葉はどれかな？", choices: ["せいりする", "ひろげる", "なくす", "わすれる"], answer: "せいりする", explanation: "正解は「せいりする」！<br>バラバラのものをひとつにきれいにすることを<b>「まとめる」や「せいりする」</b>というよ。" },
    { grade: 4, genre: "japanese", type: "select", text: "「部屋の中が明るい」の「明るい」の反対の意味の言葉はどれ？", choices: ["くらい", "おもい", "ひろい", "ちいさい"], answer: "くらい", explanation: "正解は「くらい」！<br>光（ひかり）がたくさんある「明るい」の反対は、光がない<b>「くらい」</b>だね！" },
    { grade: 4, genre: "japanese", type: "select", text: "「（ ）も歩けば棒に当たる」空欄に入る動物は？", choices: ["犬", "猫", "猿", "鳥"], answer: "犬", explanation: "正解は「犬」だよ！<br><b>「犬も歩けば棒に当たる」</b>は、何か行動を起こせば、思いがけない幸運（または災難）に遭うということわざだよ。" }
]);
// 🟦 【さんすう：math】
bulkQuestionsData.push(...[
    { grade: 4, genre: "math", type: "select", text: "1リットル（L）は、何ミリリットル（mL）の量（りょう）と同じかな？", choices: ["1000mL", "100mL", "10mL", "10000mL"], answer: "1000mL", explanation: "正解は「1000mL」！<br>mLの「m」は<b>1000分の一</b>という意味なので、1L = 1000mL になるんだよ。" },
    { grade: 4, genre: "math", type: "select", text: "長方形（ちょうほうけい）の面（めん）積（せき）を求めるための正しい公式（こうしき）はどれ？", choices: ["たて × よこ", "たて ＋ よこ", "一辺 × 一辺", "底辺 × 高さ ÷ 2"], answer: "たて × よこ", explanation: "正解は「たて × よこ」！<br>面（めん）積（せき）（ひろさ）の基本（きほん）だね。ちなみに「一辺×一辺」は<b>正方形の公式（こうしき）</b>だよ！" },
    { grade: 4, genre: "math", type: "which", text: "「平（へい）行（こう）四辺形（しへんけい）」の向かい合う辺の長さは、それぞれ等しい。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>平（へい）行（こう）四辺形（しへんけい）は、向かい合う<b>2組の辺がどちらも平（へい）行（こう）</b>で、長さも同じになるよ！" },
    { grade: 4, genre: "math", type: "select", text: "時速60kmのスピードで走る車が、2時間で進むと何km先まで行けるかな？", choices: ["120km", "30km", "60km", "180km"], answer: "120km", explanation: "正解は「120km」！<br>時速60kmとは「1時間に60km進む」という意味なので、<b>60 × 2 = 120km</b> になるよ！" },
    { grade: 4, genre: "math", type: "select", text: "角（かく）度（ど）の問題だよ。1つの「直角（ちょっかく）」は何（なん）度（ど）のことかな？", choices: ["90度", "180度", "45度", "360度"], answer: "90度", explanation: "正解は「90度（90°）」！<br>ノートの角（かど）のような正しくまっすぐな直角は<b>90度</b>、半分にすると45度になるよ。" },
    { grade: 4, genre: "math", type: "select", text: "わり算の「あまり」の問題だよ。「45 ÷ 6」の正しい答えはどれ？", choices: ["7 あまり 3", "7 あまり 2", "6 あまり 9", "8 あまり 1"], answer: "7 あまり 3", explanation: "正解は「7 あまり 3」！<br>かけ算九九で考えると <b>6 × 7 = 42</b>。引き算して 45 - 42 = 3 なので、あまりは3になるね！" },
    { grade: 4, genre: "math", type: "which", text: "分数（ぶんすう）の問題だよ。「5分の3」は「5分の2」よりも小さい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>下の数が同じなら、上の数（分子（ぶんし））が<b>大きいほう（5分の3）が全体の量（りょう）も大きくなる</b>よ！" },
    { grade: 4, genre: "math", type: "select", text: "1.4 ＋ 0.8 の正しい計（けい）算（さん）結（けっ）果（か）はどれかな？", choices: ["2.2", "1.2", "2.0", "1.12"], answer: "2.2", explanation: "正解は「2.2」！<br>小数のたし算だね。位（くらい）をそろえて、<b>14 ＋ 8 = 22</b> と同じように考えて小数点を打とう！" },
    { grade: 4, genre: "math", type: "direct", text: "「25 × 4」の計（けい）算（さん）の答えはいくつになる？（半角数字で入れてね）", choices: [], answer: "100", explanation: "正解は「100」だよ！<br>25を4回たすと100になるね。<b>「25×4＝100」</b>は算数でよく使う便利なセットだから覚えちゃおう！" },
    { grade: 4, genre: "math", type: "select", text: "1平方メートルは、何平方センチメートルと同じ広さかな？", choices: ["10000つ", "100つ", "1000つ", "1000000つ"], answer: "10000つ", explanation: "正解は「10000つ（10000㎠）」！<br>1mは100cmなので、たて100cm×よこ100cmを計（けい）算（さん）して、<b>100 × 100 = 10000</b> になるんだよ！" },
    { grade: 4, genre: "math", type: "select", text: "「丸い 円」のまんなかの点（てん）から、はじまでの長さをなんという？", choices: ["半径", "直径", "まわり", "四角"], answer: "半径", explanation: "正解は「半径（はんけい）」！<br>まんなかから はじまでの長さを<b>「半径（はんけい）」</b>、はじから はじまでの長さを「直径（ちょっけい）」というよ。" },
    { grade: 4, genre: "math", type: "which", text: "「3 ÷ 0」の答えは「0」である。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>算数では、数を<b>「0」でわることはできない</b>というルールがあるんだよ！" },
    { grade: 4, genre: "math", type: "select", text: "「15 × 6」の正しい計（けい）算（さん）の答えはどれかな？", choices: ["90", "80", "75", "100"], answer: "90", explanation: "正解は「90」！<br>10 × 6 = 60、5 × 6 = 30。あわせて <b>60 ＋ 30 = 90</b> になるね！" },
    { grade: 4, genre: "math", type: "select", text: "「1kg」は、何グラム（g）の重さと同じかな？", choices: ["1000g", "100g", "10g", "10000g"], answer: "1000g", explanation: "正解は「1000g」！<br>キロ（k）は<b>1000倍</b>という意味の記号（きごう）なので、1kg = 1000g になるんだよ！" },
    { grade: 4, genre: "math", type: "select", text: "三角形の面積を求める公式は？", choices: ["底辺 × 高さ", "半径 × 半経 × 3.14", "縦 × 横", "底辺 × 高さ ÷ 2"], answer: "底辺 × 高さ ÷ 2", explanation: "正解は「底辺 × 高さ ÷ 2」だよ！<br>四角形の面積の半分になるから、さいごの<b>「÷ 2」</b>を絶対に忘れないようにしよう！" },
    { grade: 4, genre: "math", type: "select", text: "時速60kmの車が、2時間で進む距離は？", choices: ["120km", "30km", "60km", "180km"], answer: "120km", explanation: "正解は「120km」だよ！<br>「速さ × 時間 ＝ 距離」だから、<b>60 × 2 ＝ 120</b> という計算になるね。" },
    { grade: 4, genre: "math", type: "direct", text: "25 × 4 の答えはいくつ？", choices: [], answer: "100", explanation: "正解は「100」だよ！<br><b>25 × 4 ＝ 100</b> は算数でとってもよく使う計算だから、セットで覚えておくと便利だよ！" },
    { grade: 4, genre: "math", type: "select", text: "1リットルは何ミリリットル（ml）？", choices: ["1000ml", "100ml", "10ml", "10000ml"], answer: "1000ml", explanation: "正解は「1000ml」だよ！<br>「m（ミリ）」には<b>1000分の1</b>という意味があるから、1000ml集まるとちょうど1Lになるんだよ。" },
    { grade: 4, genre: "math", type: "select", text: "三角形の面積を求める公式はどれ？", choices: ["底辺×高さ÷2", "半径×半径×3.14", "縦×横", "底辺×高さ×2"], answer: "底辺×高さ÷2", explanation: "正解は「底辺×高さ÷2」だよ！<br>「÷2」をするのを<b>絶対に忘れないように</b>しようね！" },
    { grade: 4, genre: "math", type: "select", text: "1リットル（L）は、何ミリリットル（mL）の量と同じかな？", choices: ["1000mL", "100mL", "10mL", "10000mL"], answer: "1000mL", explanation: "正解は「1000mL」！<br>mLの「m（ミリ）」は<b>1000分の一</b>という意味なので、1L = 1000mL になるんだよ。" },
    { grade: 4, genre: "math", type: "select", text: "長方形（ちょうほうけい）の面積を求めるための正しい公式はどれ？", choices: ["たて × よこ", "たて ＋ よこ", "一辺 × 一辺", "底辺 × 高さ ÷ 2"], answer: "たて × よこ", explanation: "正解は「たて × よこ」！<br>面積（つの広さ）の基本だね。ちなみに「一辺×一辺」は<b>正方形の公式</b>だよ！" },
    { grade: 4, genre: "math", type: "which", text: "「平行四辺形（へいこうしへんけい）」の向かい合う辺の長さは、それぞれ等しい。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>平行四辺形は、向かい合う<b>2組の辺がどちらも平行</b>で、長さも同じになる特徴があるよ！" },
    { grade: 4, genre: "math", type: "select", text: "時速60kmのスピードで走る車が、2時間進むと何km先まで行けるかな？", choices: ["120km", "30km", "60km", "180km"], answer: "120km", explanation: "正解は「120km」！<br>時速60kmとは「1時間に60km進む」という意味なので、<b>60 × 2 = 120km</b> になるよ！" },
    { grade: 4, genre: "math", type: "select", text: "角度（かくど）の問題だよ。1つの「直角（ちょっかく）」は何度（°）のことかな？", choices: ["90°", "180°", "45°", "360°"], answer: "90°", explanation: "正解は「90°（きゅうじゅうど）」！<br>ノートの角（かど）のような正しくまっすぐな直角は<b>90°</b>、半分にすると45°になるよ。" },
    { grade: 4, genre: "math", type: "select", text: "わり算の「あまり」の問題だよ。「45 ÷ 6」の正しい答えはどれ？", choices: ["7 あまり 3", "7 あまり 2", "6 あまり 9", "8 あまり 1"], answer: "7 あまり 3", explanation: "正解は「7 あまり 3」！<br>かけ算九九で考えると <b>6 × 7 = 42</b>。引き算して 45 - 42 = 3 なので、あまりは3になるね！" },
    { grade: 4, genre: "math", type: "which", text: "分数（ぶんすう）の問題だよ。「5分之3（3/5）」は「5分之2（2/5）」よりも小さい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>下の数（分母）が同じなら、上の数（分子）が<b>大きいほう（3/5）が全体の量も大きくなる</b>よ！" },
    { grade: 4, genre: "math", type: "select", text: "1.4 ＋ 0.8 の正しい計算結果はどれかな？", choices: ["2.2", "1.2", "2.0", "1.12"], answer: "2.2", explanation: "正解は「2.2」！<br>小数のたし算だね。位（くらい）をそろえて、<b>14 ＋ 8 = 22</b> と同じように考えて小数点を打とう！" },
    { grade: 4, genre: "math", type: "direct", text: "「15 × 5」の計算の答えはいくつになる？（半角数字で入力してね）", choices: [], answer: "75", explanation: "正解は「75」だよ！<br>15を5回たすと75になるね。" },
    { grade: 4, genre: "math", type: "select", text: "1平方メートル（㎡）は、何平方センチメートル（㎠）と同じ広さかな？", choices: ["10000㎠", "100㎠", "1000㎠", "1000000㎠"], answer: "10000㎠", explanation: "正解は「10000㎠」！<br>1mは100cmなので、たて100cm×よこ100cmを計算して、<b>100 × 100 = 10000</b> になるんだよ！" }
]);
// 🟩 【どうとく：moral】
bulkQuestionsData.push(...[
    { grade: 4, genre: "moral", type: "select", text: "図書館（としょかん）など、みんなが使う公共（こうきょう）の場所での正しい過ごし方はどれ？", choices: ["静かに過ごす", "大声で走る", "お菓子を食べる", "ゲームをおとをだしてする"], answer: "静かに過ごす", explanation: "正解は「静かに過ごす」！<br>みんなが気持ちよく本（ほん）を読めるように、周りの人への<b>「思いやり」</b>が大切だね。" },
    { grade: 4, genre: "moral", type: "select", text: "ネットで友達のわるぐちが書き込まれているのを見つけました。最も適切な行動は？", choices: ["大人や先生に相談する", "自分も一緒に書き込む", "その人を強くおこる", "友達に教えてひろげる"], answer: "大人や先生に相談する", explanation: "正解は「大人や先生に相談する」！<br>ネットのトラブルは自分だけで解決（かいけつ）せず、<span style='color:#2ecc71; font-weight:bold;'>大人や先生にすぐ報告（ほうこく）</span>しよう。" },
    { grade: 4, genre: "moral", type: "which", text: "友達との約束（やくそく）の時間に遅れそうになったとき、「だまって遅れていく」のが正しい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>遅れそうだとわかった時点で、必ず相手に <b>連絡（れんらく）をして理由を伝える</b>のが、相手を大切にするマナーだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "学級（がっきゅう）会で自分とは違う意見が出ました。そのときの正しい態度はどれ？", choices: ["最後まで理由を聞く", "すぐ大声で否定する", "無視していなくなる", "自分の意見を無理やり通す"], answer: "最後まで理由を聞く", explanation: "正解は「最後まで理由を聞く」！<br>人それぞれ違う考え方を持っているよ。まずは <b>相手の意見をしっかりと聞く</b>ことから、良い話し合いが始まるんだ。" },
    { grade: 4, genre: "moral", type: "select", text: "「自分の行動に責（せき）任（にん）を持つ」とは、具体的にどういうことかな？", choices: ["自分の失敗を認め、次につなげること", "絶対に失敗しないこと", "誰かのせいにすること", "嫌なことから逃げること"], answer: "自分の失敗を認め、次につなげること", explanation: "正解は「自分の失敗を認め、次につなげること」！<br>誰でも失敗はするよ。言い訳をせず、<b>次からどうすれば上手くいくか</b>を自分で考えることが大切だよ。" },
    { grade: 4, genre: "moral", type: "which", text: "学校の備品（ボールなど）は、みんなの物なので雑（ざつ）に扱（あつか）って壊（こわ）しても気にしなくてよい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>みんなで使う物は、次に使う人のことを考えて <b>「大切に優しく」</b> 扱うのが、立派（りっぱ）なプレイヤーのルールだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "友達が宿題を忘れて困っています。「本当の優しさ」として、最も正しい行動はどれ？", choices: ["やり方を優しく教えてあげる", "自分の宿題をそのまま写させる", "先生に見つからないよう隠す", "忘れたことをみんなに言いふらす"], answer: "やり方を優しく教えてあげる", explanation: "正解は「やり方を優しく教えてあげる」！<br>答えを写させるのは、その友達のためにならないよ。<b>ヒントをあげたり一緒に考える</b>のが本当の優しさだね。" },
    { grade: 4, genre: "moral", type: "select", text: "困っているお年寄りや、体が不自由な人が目の前にいます。どんな行動をするとよいかな？", choices: ["何か手伝えるか声をかける", "気づかないふりをして通り過ぎる", "遠くからじっと見つめている", "かわいそうだと言いふらす"], answer: "何か手伝えるか声をかける", explanation: "正解は「何か手伝えるか声をかける」！<br><b>「何かお手伝いできることはありますか？」</b>という一言が、相手にとって大きな心の支えになるんだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "クラスの係（かかり）の仕事が面倒（めんどう）になってしまいました。どう行動するのが一番良いかな？", choices: ["最後までやり遂げる方法を考える", "だまってサボる", "他の人に無理やり押し付ける", "怒って途中でやめる"], answer: "最後までやり遂げる方法を考える", explanation: "正解は「最後までやり遂げる方法を考える」！<br>自分が引き受けた役割は、<b>最後までやり遂げる</b>ことで、クラスのみんなからの「信頼（しんらい）」に繋がるよ！" },
    { grade: 4, genre: "moral", type: "select", text: "友達と口げんかをしてしまいました。仲直り（なかなおり）するために大切なことは？", choices: ["自分の悪かったところを謝る", "相手が謝るまで無視し続ける", "もっと大きな声でおこる", "もういっさい口をきかない"], answer: "自分の悪かったところを謝る", choices: ["自分の悪かったところを謝る", "相手が謝るまで無視し続ける", "もっと大きな声でおこる", "もういっさい口をきかない"], answer: "自分の悪かったところを謝る", explanation: "正解は「自分の悪かったところを謝る」！<br>相手のせいにするだけでなく、<b>自分の悪かったところを見つけて「ごめんね」</b>と言おうね！" },
    { grade: 4, genre: "moral", type: "which", text: "生き物を飼（か）うときは、途中で飽（あ）きてしまったらどこかに捨て（す）ててもよい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>生き物には大切な命（いのち）があるよ。<b>最（さい）期（ご）まで飼（か）いきる</b>のが、飼うときの大事な約束だよ！" },
    { grade: 4, genre: "moral", type: "select", text: "学校から帰ってからの時間の使い方で、一番良いのはどれかな？", choices: ["やるべきことをしてから遊ぶ", "夜遅くまでずっとゲームをする", "宿題をぜんぶサボる", "明日の準備をなにもしない"], answer: "やるべきことをしてから遊ぶ", explanation: "正解は「やるべきことをしてから遊ぶ」！<br>宿題や次の日の準備など、<b>やるべきことを先に済ませる</b>と、気持ちよく全力で遊べるね！" },
    { grade: 4, genre: "moral", type: "select", text: "クラスの友達が、なにかの係の仕事をひとりで頑張（がんば）っています。どうする？", choices: ["「何か手伝おうか？」と声をかける", "頑張っているねと笑う", "関係ないやと無視する", "もっと仕事を増やす"], answer: "「何か手伝おうか？」と声をかける", explanation: "正解は「『何か手伝おうか？』と声をかける」！<br>ひとりで大変そうなときは、<b>仲間として助け合って</b>進めていこうね！" },    
    { grade: 4, genre: "moral", type: "select", text: "図書館など、みんなが使う場所での正しい過ごし方は？", choices: ["静かに過ごす", "大声で走る", "お菓子を食べる", "ゲームを大音量でする"], answer: "静かに過ごす", explanation: "正解は「静かに過ごす」です。<br>みんなが気持ちよく本を読めるように、公共の場所では<span style='color:#2ecc71; font-weight:bold;'>マナーを守って静かに</span>しようね。" },
    { grade: 4, genre: "moral", type: "select", text: "SNSで友達の悪口を書いている人を見つけました。適切な行動は？", choices: ["関わらず、大人や先生に相談する", "自分も一緒に書き込む", "その人を強く責め立てる", "面白そうなので友達に拡散する"], answer: "関わらず、大人や先生に相談する", explanation: "正解は「関わらず、大人や先生に相談する」です。<br>トラブルに巻き込まれないよう自分は関わらず、すぐに<span style='color:#ff7675; font-weight:bold;'>大人や先生に報告</span>しよう。" },
    { grade: 4, genre: "moral", type: "select", text: "「責任（せきにん）を持つ」とはどういうこと？", choices: ["自分の失敗を認め、次につなげること", "絶対に失敗しないこと", "誰かのせいにすること", "嫌なことから逃げること"], answer: "自分の失敗を認め、次につなげること", explanation: "正解は「自分の失敗を認め、次につなげること」です。<br>失敗しても他人のせいにせず、<b>自分の行動を引き受けること</b>が本当にカッコいい大人への一歩だよ。" },
    { grade: 4, genre: "moral", type: "which", text: "友達が困っているときは、声をかけずに放っておくのが正しい行動である。○か×か？", choices: [true, false], answer: false, explanation: "正解は×（バツ）だよ！<br>なにか手伝えることがないか、<b>「どうしたの？」</b>と優しく声をかけてあげよう。" },
    { grade: 4, genre: "moral", type: "select", text: "図書館など、みんなが使う公共（こうきょう）の場所での正しい過ごし方はどれ？", choices: ["静かに過ごす", "大声で走る", "お菓子を食べる", "ゲームを大音量でする"], answer: "静かに過ごす", explanation: "正解は「静かに過ごす」！<br>みんなが気持ちよく読書や勉強をできるように、周りの人へ<b>「思いやり」</b>を持つことが大切だね。" },
    { grade: 4, genre: "moral", type: "select", text: "SNSでクラスの友達の悪口が書き込まれているのを見つけました。最も適切な行動は？", choices: ["関わらず、大人や先生に相談する", "自分も一緒に書き込む", "その人を強く責め立てる", "面白そうなので友達に拡散する"], answer: "関わらず、大人や先生に相談する", explanation: "正解は「関わらず、大人や先生に相談する」！<br>ネットのトラブルは自分だけで解決しようとせず、信頼できる<span style='color:#2ecc71; font-weight:bold;'>保護者や先生にすぐに報告</span>しよう。" },
    { grade: 4, genre: "moral", type: "which", text: "友達との約束の時間に遅れそうになったとき、「だまって遅れていく」のが正しいマナーである。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>遅れそうだとわかった時点で、必ず相手に<b>連絡をして理由を伝える</b>のが、相手を尊重する正しいマナーだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "学級会（がっきゅうかい）で自分とは違う意見が出ました。そのときの正しい態度はどれ？", choices: ["最後まで理由を聞く", "すぐに大声で否定する", "無視して席を立つ", "自分の意見を無理やり通す"], answer: "最後まで理由を聞く", explanation: "正解は「最後まで理由を聞く」！<br>人それぞれ違う考え方を持っているよ。まずは<b>相手の意見をしっかりと聞く</b>ことから、良い話し合いが始まるんだ。" },
    { grade: 4, genre: "moral", type: "select", text: "「自分の行動に責任（せきにん）を持つ」とは、具体的にどういうことかな？", choices: ["自分の失敗を認め、次につなげること", "絶対に失敗しないこと", "誰かのせいにすること", "嫌なことから逃げること"], answer: "自分の失敗を認め、次につなげること", explanation: "正解は「自分の失敗を認め、次につなげること」！<br>誰でも失敗はするよ。大切なのは言い訳をせず、<b>次からどうすれば上手くいくか</b>を自分で考えて行動することだよ。" },
    { grade: 4, genre: "moral", type: "which", text: "学校の備品（一輪車やボールなど）は、みんなの物なので雑に扱って壊しても気にしなくてよい。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>みんなで使う物は、次に使う人のことを考えて<b>「大切に優しく」</b>扱うのが、アニマル村の立派なプレイヤーのルールだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "友達が宿題を忘れて困っています。「本当の優しさ」として、最も正しい行動はどれ？", choices: ["やり方を優しく教えてあげる", "自分の宿題をそのまま写させる", "先生に見つからないよう隠す", "忘れたことをみんなに言いふらす"], answer: "やり方を優しく教えてあげる", explanation: "正解は「やり方を優しく教えてあげる」！<br>答えを写させるのは、その友達の成長のためにならないよ。<b>ヒントをあげたり一緒に考える</b>のが本当の優しさだね。" },
    { grade: 4, genre: "moral", type: "select", text: "困っているお年寄りや、体が不自由な人が目の前にいます。どんな気持ちで接するとよいかな？", choices: ["何か手伝えるか声をかける", "気づかないふりをして通り過ぎる", "遠くからじっと見つめる", "かわいそうだと言いふらす"], answer: "何か手伝えるか声をかける", explanation: "正解は「何か手伝えるか声をかける」！<br><b>「何かお手伝いできることはありますか？」</b>という一言が、相手にとって大きな心の支えになるんだよ。" },
    { grade: 4, genre: "moral", type: "select", text: "クラスの係の仕事が面倒（めんどう）になってしまいました。どう行動するのが一番良いかな？", choices: ["最後までやり遂げる方法を考える", "だまってサボる", "他の人に無理やり押し付ける", "怒って途中でやめる"], answer: "最後までやり遂げる方法を考える", explanation: "正解は「最後までやり遂げる方法を考える」！<br>自分が引き受けた役割は、<b>最後までやり遂げる（責任感）</b>ことで、クラスのみんなからの「信頼（しんらい）」に繋がるよ！" }
]);
// 🔬 【りか：science】
bulkQuestionsData.push(...[
    { grade: 4, genre: "science", type: "select", text: "水が沸（ふ）騰（とう）したときに出る泡（あわ）の正体はなに？", choices: ["水蒸気", "空気", "酸素", "二酸化炭素"], answer: "水蒸気", explanation: "正解は「水蒸気（すいじょうき）」！<br>水が熱せられて<b>気体（水蒸気）に変（へん）化（か）したもの</b>が、泡になって出てきているんだよ！" },
    { grade: 4, genre: "science", type: "select", text: "昆虫（こんちゅう）の体のつくりだよ。頭、胸（むね）ともう1つはどこ？", choices: ["腹", "足", "背中", "おしり"], answer: "腹", explanation: "正解は「腹（はら）」！<br>昆虫の体は<b>「頭・胸・腹」</b>の3つに分かれているのが大きな特徴（とくちょう）だよ。" },
    { grade: 4, genre: "science", type: "which", text: "月は太陽と同じように、東からのぼって西へ沈（しず）む。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>地球が自転（じてん）しているため、<b>太陽も月も星も</b>、すべて東から西へ動いて見えるんだよ。" },
    { grade: 4, genre: "science", type: "select", text: "春の夜空（よぞら）に見える、ひしゃくの形をした有名な星の並び（星座（せいざ）の一部）はどれ？", choices: ["北斗七星", "オリオン座", "夏の大三角", "カシオペヤ座"], answer: "北斗七星", explanation: "正解は「北斗七星（ほくとしちせい）」！<br>おおぐま座という星座（せいざ）のしっぽの部分にあたる、<b>7つの明るい星の集まり</b>だよ。" },
    { grade: 4, genre: "science", type: "select", text: "植物の育ち方だよ。ひまわりの種（たね）から最初（さいしょ）に出てくるものはどれ？", choices: ["根", "芽", "茎", "本葉"], answer: "根", explanation: "正解は「根（ね）」！<br>植物は、種からまず<b>「根」が出てきて土をしっかりつかみ</b>、そのあとに「芽」を出すんだよ。" },
    { grade: 4, genre: "science", type: "which", text: "空気は温められると、体積（たいせき）（空気の広さ）が大きくなる。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>空気や水は<b>温められると大きく広がり（体積が大きくなる）</b>、冷やされると小さくなるよ。" },
    { grade: 4, genre: "science", type: "select", text: "秋になると木の葉の色が変わる植物はどれかな？", choices: ["イチョウ", "マツ", "スギ", "サボテン"], answer: "イチョウ", explanation: "正解は「イチョウ」！<br>秋になると葉が<b>きれいな黄色に変わる</b>よ。このように葉が落ちる木を落葉樹（らくようじゅ）というよ。" },
    { grade: 4, genre: "science", type: "select", text: "人の体のつくりだよ。うでを曲げ（まげ）たとき、内側の筋肉（きんにく）はどうなるかな？", choices: ["硬くなって縮む", "柔らかくなって伸びる", "何も変わらない", "細くなる"], answer: "硬くなって縮む", explanation: "正解は「硬（かた）くなって縮（ちぢ）む」！<br>うでを曲げると<b>内側の筋肉が力を入れて縮み</b>、外側の筋肉が伸びるんだよ。" },
    { grade: 4, genre: "science", type: "which", text: "日かげの地面（じめん）は、日なたの地面よりも温度（おんど）が高い。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>太陽の光が直接（ちょくせつ）あたる<b>日なたのほうが、地面が温められて温度（おんど）が高くなる</b>よ。" },
    { grade: 4, genre: "science", type: "select", text: "ヘチマの雄花（おばな）と雌花（めばな）だよ。実（みの）になるのはどっちかな？", choices: ["雌花", "雄花", "どちらも実になる", "どちらも実にならない"], answer: "雌花", explanation: "正解は「雌花（めばな）」！<br>雌花の下のほうには<b>最初から小さなふくらみ</b>があって、これが大きくなってヘチマの実になるんだよ。" },
    { grade: 4, genre: "science", type: "select", text: "夜空（よぞら）の星の色だよ。一番温度（おんど）が高い星は次のうち何色かな？", choices: ["青白い色", "赤っぽい色", "黄色っぽい色", "オレンジ色"], answer: "青白い色", explanation: "正解は「青白い色」！<br>星は、赤っぽい色よりも<b>青白く輝（かがや）いている星のほうが、表面の温度（おんど）がとても高い</b>んだよ。" },
    { grade: 4, genre: "science", type: "which", text: "雨がふったあと、運動場（うんどうじょう）の水がなくなったのは、すべて土にしみこんだからである。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>土にしみこむだけでなく、水が<b>空気中に蒸（じょう）発（はつ）して水蒸気になった</b>からでもあるよ。" },
    { grade: 4, genre: "science", type: "select", text: "電気（でんき）を通しやすいものは次のうちどれかな？", choices: ["鉄のくぎ", "プラスチックの定規", "木のエんぴつ", "紙のノート"], answer: "鉄のくぎ", explanation: "正解は「鉄のくぎ」！<br>金（きん）属（ぞく）（鉄やアルミニウムなど）は、<b>電気（でんき）をとても通しやすい</b>特徴（とくちょう）があるよ。" },
    { grade: 4, genre: "science", type: "select", text: "冬の生きものの姿（すがた）だよ。カエルやヘビは冬の間、どうやって過ごしているかな？", choices: ["土の中で眠る", "南の国へ飛んでいく", "元気に走り回る", "海の中を泳ぐ"], answer: "土の中で眠る", explanation: "正解は「土の中で眠（ねむ）る」！<br>冬の間、土や穴（あな）の中でじっとして過ごすことを<b>「冬眠（とうみん）」</b>というんだよ。" }
]);
// 🗺️ 【しゃかい：social】
bulkQuestionsData.push(...[
    { grade: 4, genre: "social", type: "select", text: "私たちが使った汚（よご）れた水を綺麗（きれい）にして川に流す、街の大切な施設（しせつ）はどこ？", choices: ["下水処理場", "浄水場", "ゴミ処理場", "発電所"], answer: "下水処理場", explanation: "正解は「下水処理場（げすいしょりじょう）」！<br>ちなみに、川の水を綺麗にして飲み水を作る施設は<b>「浄水場（じょうすいじょう）」</b>だよ！" },
    { grade: 4, genre: "social", type: "select", text: "日本にある「都道府県（とどうふけん）」は、全部で何個あるかな？", choices: ["47個", "43個", "45個", "50個"], answer: "47個", explanation: "正解は「47個」！<br>4年生の地図で覚えるね。<b>1都1道2府43県</b>を合わせて47都道府県（とどうふけん）だよ！" },
    { grade: 4, genre: "social", type: "which", text: "災害（さいがい）の危険（きけん）がある場所を予測（よそく）した「ハザードマップ」を見ることで、避（ひ）難（なん）場所が確認（かくにん）できる。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>自分の住んでいる地域のハザードマップを事前に確（かく）認（にん）しておくことが、安全（あんぜん）のために大切だよ。" },
    { grade: 4, genre: "social", type: "select", text: "日本で一番広い「都道府県（とどうふけん）」はどこかな？", choices: ["北海道", "東京都", "岩手県", "沖縄県"], answer: "北海道", explanation: "正解は「北海道（ほっかいどう）」！<br>日本の北にある<b>北海道が一番広い</b>よ。ちなみに2番目に広いのは岩手県（いわてけん）だよ！" },
    { grade: 4, genre: "social", type: "select", text: "私たちが集めた燃（も）えるゴミは、ゴミ処理（しょり）場で最初（さいしょ）にどうされるかな？", choices: ["燃やして灰にする", "土にそのまま埋める", "海にすべて流す", "リサイクルして服にする"], answer: "燃やして灰にする", explanation: "正解は「燃（も）やして灰（はい）にする」！<br>ゴミを燃やして量を小さくしてから、残った灰を処分（しょり）場に埋（う）め立てるんだよ。" },
    { grade: 4, genre: "social", type: "which", text: "警察（けいさつ）署（しょ）で働くおまわりさんは、火事（かじ）が起きたときに火を消すのが一番の仕事である。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br>火を消すのは<b>消防署（しょうぼうしょ）の仕事</b>だよ。おまわりさんは、街のパトロールや事件（じけん）を防ぐのが仕事だよ。" },
    { grade: 4, genre: "social", type: "select", text: "昔からその地域（ちいき）に伝わる、お祭り（まつり）や道具、建物のことをまとめてなんと呼ぶかな？", choices: ["伝統的な文化", "最新の流行", "個人の趣味", "外国の文化"], answer: "伝統的な文化", explanation: "正解は「伝統（でんとう）的な文化（ぶんか）」！<br>大昔から親から子へと<b>大切に受け継が（うけつが）れてきた、地域の宝物</b>のことだね。" },
    { grade: 4, genre: "social", type: "select", text: "私たちが毎日使っている「水道の水」は、もともとどこから集められたものかな？", choices: ["川やダム", "海の水", "雨の水をそのまま", "お店で買った水"], answer: "川やダム", explanation: "正解は「川やダム」！<br>川やダムから集めた水を、<b>浄水場（じょうすいじょう）で綺麗（きれい）にして</b>からお家に届けているんだよ。" },
    { grade: 4, genre: "social", type: "which", text: "都道府県（とどうふけん）の中で、まわりがすべて海に囲ま（かこま）れている島国のような県は「沖縄（おきなわ）県」である。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>日本の南にある<b>沖縄県は、たくさんの美しい島が集まってできている県</b>なんだよ。" },
    { grade: 4, genre: "social", type: "select", text: "事件（じけん）や事故（じこ）が起きたとき、警察（けいさつ）に連絡（れんらく）するための正しい電話番号はどれ？", choices: ["110番", "119番", "117番", "104番"], answer: "110番", explanation: "正解は「110番」！<br>おまわりさんを呼ぶときは<b>110番</b>。ちなみに消防車や救急車を呼ぶときは<b>119番</b>だよ！" },
    { grade: 4, genre: "social", type: "select", text: "日本の一番南にある都道府県（とどうふけん）はどこかな？", choices: ["沖縄県", "鹿児島県", "東京都", "北海道"], answer: "東京都", explanation: "正解は「東京都（とうきょうと）」！<br>ひっかけ問題だね。実は小笠原（おがさわら）諸島（しょとう）の<b>「沖ノ鳥島（おきのとりしま）」が日本の一番南</b>にあり、そこは東京都なんだよ！" },
    { grade: 4, genre: "social", type: "which", text: "ゴミを減らすための「3R（スリーアール）」で、いらない物を「断る（ことわる）」ことをリデュースという。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br>ゴミそのものを<b>最初（さいしょ）から出さないように減らす（Reduce）</b>という、とても大切な考え方だよ。" },
    { grade: 4, genre: "social", type: "select", text: "地震（じしん）が起きたとき、家の中で最初（さいしょ）にとるべき安全（あんぜん）な行動はどれ？", choices: ["机の下に隠れて頭を守る", "いそいで外へ飛び出す", "荷物をたくさんまとめる", "窓を全部閉め切る"], answer: "机の下に隠れて頭を守る", explanation: "正解は「机（つくえ）の下に隠（かく）れて頭（あたま）を守る」！<br>家具（かぐ）が倒れ（たおれ）てきたり、物が落ちてくるのから<b>身を守ることが一番大切</b>だよ。" },
    { grade: 4, genre: "social", type: "select", text: "都道府県（とどうふけん）のリーダー（一番上の責任者（せきにんしゃ））をなんと呼ぶかな？", choices: ["知事", "総理大臣", "市長", "校長先生"], answer: "知事", explanation: "正解は「知事（ちじ）」！<br>東京都知事や大阪府知事のように、<b>それぞれの都道府県（とどうふけん）をまとめるリーダー</b>のことだよ。" }
]);
bulkQuestionsData.push(...[
    { grade: 4, genre: "english", type: "select", text: "英語で「日曜（にちようび）」を表す正しい単語（たんご）はどれかな？", choices: ["Sunday", "Monday", "Friday", "Saturday"], answer: "Sunday", explanation: "正解は「Sunday（サンデー）」！<br>カレンダーの一番左側にある、みんなが大好きな<b>日曜日</b>だね！" },
    { grade: 4, genre: "english", type: "select", text: "英語で「12（じゅうに）」を数えるときの正しい言い方はどれ？", choices: ["twelve", "eleven", "twenty", "ten"], answer: "twelve", explanation: "正解は「twelve（トゥエルブ）」！<br>ちなみに「eleven」は11、時計（とけい）の数字を英語で言えるようになるとかっこいいよ！" },
    { grade: 4, genre: "english", type: "direct", text: "「ありがとう」を英語でいうと「Thank （ ）」。カッコに入る英単語は？（全部小文字でね）", choices: [], answer: "you", explanation: "正解は「you（ユー）」だよ！<br>合わせて<b>「Thank you（サンキュー）」</b>、感謝（かんしゃ）を伝える素敵な言葉だね！" },
    { grade: 4, genre: "english", type: "select", text: "英語で「リンゴ（林檎）」を指す正しい単語（たんご）はどれかな？", choices: ["apple", "banana", "orange", "peach"], answer: "apple", explanation: "正解は「apple（アップル）」！<br>幼児（ようじ）のときにも習ったかな？真っ赤でおいしい果物（くだもの）だね！" },
    { grade: 4, genre: "english", type: "select", text: "英語で「金曜日（きんようび）」を表す正しい単語（たんご）はどれかな？", choices: ["Friday", "Tuesday", "Thursday", "Wednesday"], answer: "Friday", explanation: "正解は「Friday（フライデー）」！<br>平日の最後（さいご）の日曜日（にちようび）の手前の、わくわくする曜日（ようび）だね！" },
    { grade: 4, genre: "english", type: "which", text: "英語のあいさつ「Good morning」は、夜（よる）ねる前に使う言葉である。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br><b>Good morning（グッドモーニング）</b> は「おはよう」という、<b>朝（あさ）一番に使う言葉</b>だよ。" },
    { grade: 4, genre: "english", type: "select", text: "英語で動物（どうぶつ）の「くま（熊）」を指す正しい単語（たんご）はどれかな？", choices: ["bear", "lion", "tiger", "rabbit"], answer: "bear", explanation: "正解は「bear（ベア）」！<br>テディベアの「ベア」だね。山の中にすんでいる大きなどうぶつだよ！" },
    { grade: 4, genre: "english", type: "select", text: "学校（がっこう）で使う「えんぴつ（鉛筆）」を英語でいうとどれかな？", choices: ["pencil", "notebook", "eraser", "ruler"], answer: "pencil", explanation: "正解は「pencil（ペンシル）」！<br>毎日お勉強（べんきょう）で使う大事な道具だね。ちなみに消しゴムは「eraser」というよ。" },
    { grade: 4, genre: "english", type: "which", text: "英語で別れ（わかれ）のあいさつをするときは「Goodbye」という。○か×か？", choices: [true, false], answer: true, explanation: "正解は ○（まる）！<br><b>Goodbye（グッドバイ）</b> や「See you」と言うと、<b>「さようなら、またね」</b>という意味（いみ）になるよ！" },
    { grade: 4, genre: "english", type: "select", text: "色（いろ）の問題だよ。英語で「緑色（みどりいろ）」を指す正しい単語（たんご）はどれかな？", choices: ["green", "yellow", "purple", "white"], answer: "green", explanation: "正解は「green（グリーン）」！<br>森（もり）の木々やはっぱのような、綺麗な<b>緑色は green</b> というんだよ！" },
    { grade: 4, genre: "english", type: "select", text: "英語で「20（にじゅう）」を数えるときの正しい言い方はどれかな？", choices: ["twenty", "thirty", "ten", "thirteen"], answer: "twenty", explanation: "正解は「twenty（トゥエンティ）」！<br>10は ten、20は <b>twenty</b>。大きな数（かず）の英語だね！" },
    { grade: 4, genre: "english", type: "which", text: "英語の「milk」は、くだものの「ぶどうジュース」のことである。○か×か？", choices: [true, false], answer: false, explanation: "正解は ×（バツ）！<br><b>milk（ミルク）</b> は、みんなが給食（きゅうしょく）などで毎日飲む白い<b>「牛乳（ぎゅうにゅう）」</b>のことだよ！" },
    { grade: 4, genre: "english", type: "select", text: "英語で自分の大好きな「お父さん」を呼ぶときの言葉はどれかな？", choices: ["father", "mother", "brother", "sister"], answer: "father", explanation: "正解は「father（ファザー）」！<br>ファミリー（家族（かぞく））の単語だね。ちなみに「mother」はお母さんのことだよ！" },
    { grade: 4, genre: "english", type: "select", text: "自分の「誕生日（たんじょうび）」をお祝い（おいわい）してもらうときの正しい英語フレーズはどれ？", choices: ["Happy Birthday", "Merry Christmas", "Happy New Year", "Good luck"], answer: "Happy Birthday", explanation: "正解は「Happy Birthday（ハッピーバースデー）」！<br>年に一度（いちど）の大切な日（ひ）に、みんなで歌って伝える<b>お祝いの言葉</b>だね！" },
    { grade: 4, genre: "english", type: "direct", text: "英語で「本（ほん）」を指す正しい単語（たんご）はなに？（全部小文字4文字で入れてね）", choices: [], answer: "book", explanation: "正解は「book（ブック）」だよ！<br>教科書（きょうかしょ）や物語の本など、読むための本は全部 <b>book</b> というんだよ！" }
]);

// ==========================================
// 🎒 小学校5年生向け（grade: 5）クイズデータ追加
// ==========================================
// 🟥 【全教科】
bulkQuestionsData.push(...[
    { grade: 5, genre: "japanese", type: "select", text: "「比（ひ）率（りつ）」と同じ意味を持つ言葉はどれかな？", choices: ["割合", "合計", "倍数", "平均"], answer: "割合", explanation: "せいかいは「割合」！<br>全体に対する数量の割合を<b>「比（ひ）率（りつ）」</b>と言うよ！" },
    { grade: 5, genre: "japanese", type: "select", text: "ニュースなどで情報を「提（てい）供（きょう）」すると言うときの正しい意味はどれかな？", choices: ["役立つものを差し出すこと", "ものを隠すこと", "新しく作り出すこと", "ものを捨てること"], answer: "役立つものを差し出すこと", explanation: "せいかいは「役立つものを差し出すこと」！<br>情報や材料を相手に役立ててもらうために差し出すことを<b>「提（てい）供（きょう）」</b>と言うよ！" },
    { grade: 5, genre: "japanese", type: "select", text: "「状況に 適（てき）応（おう）する」の「適（てき）応（おう）」の正しい意味はどれかな？", choices: ["その場によくあてはまること", "その場から逃げ出すこと", "別のものを新しく作ること", "間違えてしまうこと"], answer: "その場によくあてはまること", explanation: "せいかいは「その場によくあてはまること」！<br>まわりの環境や状態にうまく合わせることを<b>「適（てき）応（おう）」</b>と言うよ！" },
    { grade: 5, genre: "japanese", type: "select", text: "「みんなを 引（いん）導（どう）する」という言葉の使い方は正しいかな？", choices: ["まちがい（正しくは 誘導 や 案内）", "正しい"], answer: "まちがい（正しくは 誘導 や 案内）", explanation: "せいかいは「まちがい」！<br>「引（いん）導（どう）」は亡くなった人を仏の道へ導く仏教の言葉なので、普段の案内には<b>「誘（ゆう）導（どう）」</b>などを使おう！" },
    { grade: 5, genre: "japanese", type: "select", text: "「劇を 上（じょう）演（えん）する」というときの「上（じょう）演（えん）」の正しい意味はどれかな？", choices: ["観客の前で劇をして見せること", "劇の練習をすること", "劇の台本を書くこと", "劇の道具を片付けること"], answer: "観客の前で劇をして見せること", explanation: "せいかいは「観客の前で劇をして見せること」！<br>舞台などで劇を実際にやって観客に見せることを<b>「上（じょう）演（えん）」</b>と言うよ！" },
    { grade: 5, genre: "japanese", type: "select", text: "「先生が 講（こう）話（わ）をする」というときの「講（こう）話（わ）」の正しい意味はどれかな？", choices: ["ある内容について分かりやすく話すこと", "大声で怒ること", "秘密の話をすること", "歌を歌うこと"], answer: "ある内容について分かりやすく話すこと", explanation: "せいかいは「ある内容について分かりやすく話すこと」！<br>大勢の人に向けて、ためになる話を分かりやすく説明することを<b>「講（こう）話（わ）」</b>と言うよ！" },
    { grade: 5, genre: "math", type: "select", text: "三角形の面積を求める公式はどれかな？", choices: ["底辺 × 高さ ÷ 2", "底辺 × 高さ", "辺 × 辺", "（上底 ＋ 下底）× 高さ ÷ 2"], answer: "底辺 × 高さ ÷ 2", explanation: "せいかいは「底辺 × 高さ ÷ 2」！<br>三角形の面積は、長方形の面積の半分になるから<b>「÷ 2」</b>をするのを忘れないようにしよう！" },
    { grade: 5, genre: "math", type: "select", text: "ある数をもとにしたとき、比べられる量がもとの数の何倍にあたるかを表した数値を何と言うかな？", choices: ["割合", "倍数", "約数", "平均"], answer: "割合", explanation: "せいかいは「割合」！<br>割合は<b>「比べられる量 ÷ もとにする量」</b>で計算することができるよ！" },
    { grade: 5, genre: "math", type: "select", text: "100円の商品の消費税が10%のとき、支払う総（そう）額（がく）はいくらになるかな？", choices: ["110円", "100円", "101円", "120円"], answer: "110円", explanation: "せいかいは「110円」！<br>100円の10%は10円なので、商品の代金と合わせて<b>100 ＋ 10 ＝ 110円</b>になるよ！" },
    { grade: 5, genre: "math", type: "select", text: "2mの重さが60gの針金があります。この針金1mの重さは何gかな？", choices: ["30g", "120g", "20g", "15g"], answer: "30g", explanation: "せいかいは「30g」！<br>1mあたりの重さを求めるので、全体の重さを長さで割って<b>60 ÷ 2 ＝ 30g</b>になるよ！" },
    { grade: 5, genre: "math", type: "select", text: "角柱の体積を求める公式はどれかな？", choices: ["底面積 × 高さ", "底面積 × 高さ ÷ 2", "底辺 × 高さ", "辺 × 辺 × 辺"], answer: "底面積 × 高さ", explanation: "せいかいは「底面積 × 高さ」！<br>角柱の体積は、底面の面積（底面積）に高さを掛（か）けることで 測（そく）定（てい） できるよ！" },
    { grade: 5, genre: "math", type: "select", text: "0.4 を分数で表すとどれになるかな？", choices: ["5分の2", "4分の1", "10分の40", "5分の4"], answer: "5分の2", explanation: "せいかいは「5分の2」！<br>0.4は10分の4だね。分子と分母を2で約分すると<b>「5分の2」</b>になるよ！" },
    { grade: 5, genre: "science", type: "select", text: "植物の種子が発芽するために、絶対に必要ないものはどれかな？", choices: ["日光", "水", "空気", "適当な温度"], answer: "日光", explanation: "せいかいは「日光」！<br>発芽に必要なのは<b>「水・空気・適当な温度」</b>の3つだよ。日光は発芽した後の成長に必要になるんだ！" },
    { grade: 5, genre: "science", type: "select", text: "メダカのたまごの中の赤ちゃんは、主に何という栄養を吸収して成長するかな？", choices: ["養分（卵黄）", "水", "空気中の酸素", "まわりの水草"], answer: "養分（卵黄）", explanation: "せいかいは「養分（卵黄）」！<br>たまごの中にある黄色っぽい球（たま）のような部分が、成長に必要な<b>養分（ようぶん）</b>になっているよ！" },
    { grade: 5, genre: "science", type: "select", text: "台風は、日本に接近するとき一般的にどちらの方角からどちらの方角へ進むことが多いかな？", choices: ["南西から北東", "北から南", "東から西", "南東から北西"], answer: "南西から北東", explanation: "せいかいは「南西から北東」！<br>日本の上空にある「偏（へん）西（せい）風（ふう）」という西からの風に乗るため、<b>南西から北東へ</b>進むことが多いよ！" },
    { grade: 5, genre: "science", type: "select", text: "ヒトの体内で、お腹の中の赤ちゃんに栄養や酸素を送るための特別な器官を何と言うかな？", choices: ["胎盤", "心臓", "胃", "へそのお"], answer: "胎盤", explanation: "せいかいは「胎盤」！<br>お母さんのお腹の中にある<b>「胎盤（たいばん）」</b>を通して、栄養や酸素が赤ちゃんに送られるんだよ！（へそのお は胎盤と赤ちゃんを繋ぐ管だよ）" },
    { grade: 5, genre: "science", type: "select", text: "水溶液に溶けている物質を、再び結晶として取り出す操作を何と言うかな？", choices: ["再結晶", "ろ過", "蒸発", "溶解"], answer: "再結晶", explanation: "せいかいは「再結晶」！<br>一度溶かした物質を、温度を下げたり水を蒸発させたりして再び純粋な結晶にする操作を<b>「再結晶（さいけっしょう）」</b>と言うよ！" },
    { grade: 5, genre: "science", type: "select", text: "ヨウ素液を落とすと、青紫色に変化する植物の栄養分は何かな？", choices: ["デンプン", "脂肪", "タンパク質", "砂糖"], answer: "デンプン", explanation: "せいかいは「デンプン」！<br>ヨウ素液は<b>「デンプン」</b>に反応して青紫色に変わる特徴があるよ。ジャガイモなどにたくさん含まれているね！" },
    { grade: 5, genre: "social", type: "select", text: "日本で使われている米の多くは、どこから 輸（ゆ）入（にゅう） されているかな？", choices: ["国内でほぼ自給している", "アメリカ", "タイ", "オーストラリア"], answer: "国内でほぼ自給している", explanation: "せいかいは「国内でほぼ自給している」！<br>日本の主食であるお米は、ほとんどを<b>日本国内の田んぼ</b>で作っていて、自給率がとても高い農産物だよ！" },
    { grade: 5, genre: "social", type: "select", text: "外国から製品を輸入するときに、国内の産業を守るためにかけられる税金を何と言うかな？", choices: ["関税", "消費税", "所得税", "住民税"], answer: "関税", explanation: "せいかいは「関税」！<br>海外からの安い製品がたくさん入ってきて国内の産業が困らないように、輸入時にかける税金を<b>「関税（かんぜい）」</b>と言うよ！" },
    { grade: 5, genre: "social", type: "select", text: "日本の国土の約何割が、森林で占められているかな？", choices: ["約7割", "約3割", "約5割", "約9割"], answer: "約7割", explanation: "せいかいは「約7割」！<br>山が多くて自然が豊かな日本の国土は、全体の<b>約7割（約3分の2）</b>が森林で覆（おお）われているんだよ！" },
    { grade: 5, genre: "social", type: "select", text: "自動車などの工業製品を、ベルトコンベアなどを使って同じ工場で大量に組み立てる工業の仕組みを何と言うかな？", choices: ["ライン生産方式", "受注生産方式", "手作業方式", "個数限定方式"], answer: "ライン生産方式", explanation: "せいかいは「ライン生産方式」！<br>作業を 複（ふく）雑（ざつ） にせず、流れてくる製品に次々と部品を取り付けて効率よく大量生産する仕組みを<b>「ライン生産方式」</b>と言うよ！" },
    { grade: 5, genre: "social", type: "select", text: "現在の日本の政治の最高法規であり、国の基本的な仕組みや人権を守るルールが書かれた法律を何と言うかな？", choices: ["日本国憲法", "明治憲法", "刑法", "民法"], answer: "日本国憲法", explanation: "せいかいは「日本国憲法」！<br>1947年に施行された<b>「日本国憲（けん）法（ぽう）」</b>は、国のすべての法律の基本となる一番大切なきまりだよ！" },
    { grade: 5, genre: "social", type: "select", text: "日本で国会などの政治を行う 政（せい）権（けん） を選ぶために、国民が行う大切な行動は何かな？", choices: ["選挙", "デモ", "アンケート", "裁判"], answer: "選挙", explanation: "せいかいは「選挙」！<br>国民の代表者を選んで政治を託（たく）すために、満18歳以上の国民全員に与えられている大切な権利が<b>「選挙（せんきょ）」</b>だよ！" },
    { grade: 5, genre: "moral", type: "select", text: "友達が意地悪をされているのを見かけました。心がけるべき一番 善（ぜん） 意（い） ある行動はどれかな？", choices: ["信頼できる大人や先生に相談する", "気づかないふりをして通り過ぎる", "自分も一緒になって意地悪をする", "遠くからスマホで動画を撮る"], answer: "信頼できる大人や先生に相談する", explanation: "せいかいは「信頼できる大人や先生に相談する」！<br> 悪（あく） 行（ぎょう） を見過ごさず、自分だけで解決しようとせずに先生や保護者に話すことが一番安全で優しい解決への一歩だよ！" },
    { grade: 5, genre: "moral", type: "select", text: "みんなで使う公園の遊具が壊れかけているのを見つけました。適切な行動はどれかな？", choices: ["近くの役所や管理している大人に知らせる", "そのまま気にせず遊び続ける", "もっと壊してみる", "インターネットのSNSに悪口を書く"], answer: "近くの役所や管理している大人に知らせる", explanation: "せいかいは「近くの役所や管理している大人に知らせる」！<br>みんなが安全に使えるように、不具合を見つけたら<b>管理している大人</b>に教えてあげよう！" },
    { grade: 5, genre: "moral", type: "select", text: "約束の時間にどうしても遅れてしまいそうなとき、最初にするべき誠実な対応は何かな？", choices: ["遅れることが分かった時点で相手に連絡する", "何も言わずに走って向かう", "行くのをやめて家に帰る", "相手が怒るのを待つ"], answer: "遅れることが分かった時点で相手に連絡する", explanation: "せいかいは「遅れることが分かった時点で相手に連絡する」！<br>相手を心配させたり 評（ひょう）判（ばん） を下げたりしないよう、<b>事前に状況を伝えること</b>が信頼を守るマナーだよ！" },
    { grade: 5, genre: "moral", type: "select", text: "クラスの話し合いで、自分とは全く違う意見が出ました。話し合いの態度として間違っているものはどれかな？", choices: ["相手の意見を途中で遮って強く批判する", "最後まで相手の理由を聞く", "どうしてそう考えたのか質問する", "自分の意見とどこが違うか比べる"], answer: "相手の意見を途中で遮って強く批判する", explanation: "せいかいは「相手の意見を途中で遮って強く批判する」！<br>違う意見であっても、頭ごなしに 批（ひ）判（はん） せず、まずは<b>お互いの考えを尊重して聴くこと</b>が大切だよ！" },
    { grade: 5, genre: "moral", type: "select", text: "掃除の時間、サボっている友達がいました。注意しても聞いてくれません。どうするのが良いかな？", choices: ["自分は自分の担当場所をしっかりと綺麗にする", "自分も一緒にサボる", "友達を強く叩いて怒る", "その友達の机を隠す"], answer: "自分は自分の担当場所をしっかりと綺麗にする", explanation: "せいかいは「自分は自分の担当場所をしっかりと綺麗にする」！<br>他人の行動に流されず、<b>自分のやるべき責任</b>をしっかりと果たすことが素晴らしい態度だね！" },
    { grade: 5, genre: "moral", type: "select", text: "友達の持ち物をうっかり壊してしまいました。最初に行うべき正しい行動は何かな？", choices: ["素直に謝罪して壊したことを伝える", "隠して元の場所に戻す", "他の人が壊したことにする", "新しいものを内緒で買ってすり替える"], answer: "素直に謝罪して壊したことを伝える", explanation: "せいかいは「素直に謝罪して壊したことを伝える」！<br>失敗してしまったときは、嘘をつかずにしっかりと 謝（しゃ）罪（ざい） し、<b>正直に話すこと</b>が一番大切だよ！" },
    { grade: 5, genre: "english", type: "select", text: "英語で「木（き）」を表す単語はどれかな？", choices: ["tree", "flower", "grass", "river"], answer: "tree", explanation: "せいかいは「tree」！<br>森や公園にたくさん生えている大きな木は英語で<b>「tree（ツリー）」</b>と言うよ！" },
    { grade: 5, genre: "english", type: "select", text: "「私は野球が好きです」と英語で言いたいとき、空欄に入る単語はどれかな？「I （　） baseball.」", choices: ["like", "play", "watch", "have"], answer: "like", explanation: "せいかいは「like」！<br>〜が好き、という気持ちを表すときは<b>「like（ライク）」</b>の単語を当てはめるよ！" },
    { grade: 5, genre: "english", type: "select", text: "英語の挨拶（あいさつ）で「こんにちは」を意味する一般的な言葉はどれかな？", choices: ["Hello", "Goodbye", "Thank you", "Sorry"], answer: "Hello", explanation: "せいかいは「Hello」！<br>時間に関係なくいつでも使える「こんにちは」の挨拶は<b>「Hello（ハロー）」</b>だね！" },
    { grade: 5, genre: "english", type: "select", text: "果物の「バナナ」の正しい英語のつづりはどれかな？", choices: ["banana", "bananna", "banan", "vanana"], answer: "banana", explanation: "せいかいは「banana」！<br>日本語の音と似ているけれど、アルファベットでは<b>「b・a・n・a・n・a」</b>と書くよ！" },
    { grade: 5, genre: "english", type: "select", text: "英語で「12」を表す単語はどれかな？", choices: ["twelve", "eleven", "twenty", "ten"], answer: "twelve", explanation: "せいかいは「twelve」！<br>11はeleven、<b>12はtwelve（トゥエルブ）</b>と言うんだよ。セットで覚えておこう！" },
    { grade: 5, genre: "english", type: "select", text: "英語で「月曜日」を表す単語はどれかな？", choices: ["Monday", "Sunday", "Friday", "Tuesday"], answer: "Monday", explanation: "せいかいは「Monday」！<br>1週間の始まりの月曜日は英語で<b>「Monday（マンデー）」</b>と言うよ。最初のMは大文字で書こう！" }
]);
